### ISSUE TITLE
Get hotspot as a layer

### ISSUE THREAD

**Issue by vincentlel** [earthdaily/qgis-plugin#101]
While requesting Hotspot, see [here](https://github.com/GEOSYS/qgis-plugin/issues/100), the API will return the following hotspot object:

```json
hotSpots": [
{
"geometry": "POINT (-100.26517713 38.99869576)",
"segmentId": 1
},
{
"geometry": "POINT (-100.26977919 38.99869091)",
"segmentId": 2
},
{
"geometry": "POINT (-100.27306991 38.99872395)",
"segmentId": 3
```

The goal is to convert these information into a shapefile layer. So hotspot points will have to be converted into a shapefile layer stored in the Map Output Directory.

The layer will be added to the map view.

See #100

**Comment by vincentlel** [comment]
Good to go

**Comment by Samweli** [comment]
Closed in https://github.com/GEOSYS/qgis-plugin/pull/108
