### ISSUE TITLE
Change detection integration

### ISSUE THREAD

**Issue by vincentlel** [earthdaily/qgis-plugin#103]
Change index is a new analytics (value from 1 to 10) that assess the level of change between 2 NDVI or EVI maps acquired on the same field or polygon. The delay between image should be between **5 and 15 days** so this change index might not be available all the time.
Once you request the coverage for a geometry you will get a field ID that you can use to fetch the change index as below:

https://api-pp.geosys-na.net/change-detection-metrics/v0/seasonfield-changedetectionmetric?%24offset=0&%24limit=20&%24count=false&SeasonfieldId=5nl35la 

here is the answer:

```json
 {
    "id": "25CSCet0CaNH3IEPx6xBh6",
    "changeIndex": 4.68610416790963,
    "companyId": null,
    "comparedImageDate": "2019-11-17T23:42:27Z",
    "comparedImageId": 346967,
    "comparedImageSensor": "S2",
    "covariance": 0.73842,
    "cropId": "5pjypl",
    "histogrammMatch": 0.94624,
    "index": "NDVI",
    "pearsonCoeff": 0.10163,
    "referenceImageDate": "2019-11-25T23:18:40Z",
    "referenceImageId": 349109,
    "referenceImageSensor": "L8",
    "requestDate": "2020-03-18T05:00:00Z",
    "requestSensors": "DE1,L8,S2,UK2",
    "seasonfieldId": "5nl35la",
    "sowingDate": "2017-04-12T05:00:00Z",
    "userId": "ex1zgyz"
  },
```
The change index value is defined for the “reference image” 

We would like to show the change index on the coverage result screen for NDVI and EVI map type 
 (see attachment) when the image date of the coverage and the referenceImagDate from the change index API are matching as below

The Postman collection shared by email provides example of change index fetching

**Comment by vincentlel** [comment]
![QGIS_CD](https://user-images.githubusercontent.com/48972214/76987030-80d41f80-6910-11ea-859d-27ea2f0206b1.png)

**Comment by timlinux** [comment]
This feature is on hold right now pending further input from GeoSYS. @VincentLel to update this ticket when they are ready to go.

**Comment by timlinux** [comment]
Need to put a link in the help pointing to guidance docs (@VincentLel to share link) that explains constraints about using the change detection index, significance of the score etc.

In the implementation we will probab do a two phased query.

1) Normal query as currently implemented which will return the icon list 
2) Secord query will add a new column to the results list with scores (rather than circular bardge as shown above)

Again @VincentLel will confirm so hold on implementing right now.

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/77075205-e5af7880-69e9-11ea-9b39-dd329f334f45.png)
