### ISSUE TITLE
Zoned map not properly displayed, shift on the map view

### ISSUE THREAD

**Issue by vincentlel** [earthdaily/qgis-plugin#112]
After selecting one polygon on my layer, I launched the search for images and selected one. The NDVI map is displayed properly (see screenshot)

I am setting the number to 6 and requesting the map and the map is not displayed on the top of the previous one.
![pboverlayzonednmap](https://user-images.githubusercontent.com/48972214/80804720-9aa58b00-8b7b-11ea-929f-2073743c76c1.png)

This issue might be related with the fact that the zoned map files loaded in the working folder has exactly the same name as the NDVI map (see screenshot 2). I have 2 layers but only one set of file so while asking the second map it might overwrite files of the first one.
![pboverlayzonednmap2](https://user-images.githubusercontent.com/48972214/80805020-7a2a0080-8b7c-11ea-84dc-7a8cdf676572.png)

Even if I am asking a new zoned map with a new date and without asking first an NDVI, the the shit is still there. But when asking for a shp format the positioning on the map is fine ( see screenshot)

**Comment by vincentlel** [comment]
![pboverlayzonednmap3](https://user-images.githubusercontent.com/48972214/80805304-49969680-8b7d-11ea-8e5d-0b7f9e3e851e.png)

**Comment by vincentlel** [comment]
The root cause of the issue might be related with the fact that you are not requesting the pgw information nor the legend with the zoning parameter in the URL (see screenshot pgw information are the same for both map)
While requesting the API to get th
![samepgwfile ](https://user-images.githubusercontent.com/48972214/80806303-ed814180-8b7f-11ea-8122-7b0d3729e002.png)
e pgw file for a NDVI map and a zoned NDVI map, the pgw are not the same 

when I request the pgw for the NDVI map 
http://api-pp.geosys-na.net/field-level-maps/v4/season-fields/bgw95dz/coverage/2019-11-27/base-reference-map/DIFFERENCE_INSEASON_NDVI/difference-with/2019-11-26/world-file.pgw

And here is the response 
4.4915764205993E-05
0
0
-3.58032460798796E-05
-97.7006431621179
37.1476945283769

When requesting for the zoned map 
http://api-pp.geosys-na.net/field-level-maps/v4/season-fields/bgw95dz/coverage/2019-11-27/base-reference-map/DIFFERENCE_INSEASON_NDVI/difference-with/2019-11-26/world-file.pgw_**?zoning=true&ZoneCount=3**_

Please note that zoning options have been added in the request and here is the answer 
1.2701234375001E-05
0
0
-1.27012343750099E-05
-97.7016753681328
37.1491377731328

**Comment by Samweli** [comment]
Ok @VincentLel, I see.

**Comment by vincentlel** [comment]
Let me know if you need a postman collection to run unit test. I already provided one before project start but happy to help if needed

**Comment by Samweli** [comment]
Thanks @VincentLel , I do have it already.
