### ISSUE TITLE
No segment layer when asking Hotspot per polygon

### ISSUE THREAD

**Issue by vincentlel** [earthdaily/qgis-plugin#113]
When asking Hotspot per polygon, only the hotspot layer is created the segment layer is missing.
![hotspot](https://user-images.githubusercontent.com/48972214/80806622-cc6d2080-8b80-11ea-8b35-9e5db03cc4f1.png)

#102  the segment layer has to be created

**Comment by vincentlel** [comment]
The layer should not be scratch layer but a shapefile in the export folder

**Comment by vincentlel** [comment]
Hi Samweli, we know have each layer loaded BUT
the layer does not have shx file so it is unusable when reloading the project.
the naming of the layer do not follow the pattern in place so it is only possible to have one hotspot and segment layer. Could you please use the following pattern HotspotPerpart_<MAPTYPE>_<FIELDID>_<DATE> and we could have HotspotPerPolygon 
Simalar naming approach should be used with segment SegmentPerpart_<MAPTYPE>_<FIELDID>_<DATE> and SegmentPerPolygon_<MAPTYPE>_<FIELDID>_<DATE>

**Comment by vincentlel** [comment]
the display of the png zoned map is still wrong and the issue above as not been fixed.

**Comment by Samweli** [comment]
> the layer does not have shx file so it is unusable when reloading the project

Hi Vincent, I can't reproduce this issue, on my side each layer shapefile have the shx file, which QGIS version are you using? So I can also test on it, thanks.

> Could you please use the following pattern HotspotPerpart_ and we could have HotspotPerPolygon
> Simalar naming approach should be used with segment SegmentPerpart_ and SegmentPerPolygon_

Sure

**Comment by Samweli** [comment]
> the display of the png zoned map is still wrong and the issue above as not been fixed.

This is fixed here https://github.com/GEOSYS/qgis-plugin/pull/116
