### ISSUE TITLE
Add LAI map product type

### ISSUE THREAD

**Issue by Samweli** [earthdaily/qgis-plugin#124]
Update the current map product type list when searching for coverage and include a INSEASON_LAI map type entry.

**Update**
This feature is available for all regions.

Example request for the INSEASON_LAI map type coverages

```
curl --location --request GET \
'http://api-pp.geosys-na.net/field-level-maps/v4/season-fields/e9yr2pm/coverage/{{image_id}}/base-reference-map/INSEASON_LAI' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer **Replace with token**'
```

Screenshot showing where to add the new map type
![image](https://user-images.githubusercontent.com/2663775/149908289-249af262-4ef0-4cf6-bea2-a0910d330f72.png)

**Comment by LNArtus** [comment]
This feature is available for all region.
Would it be possible to used the image id from the coverage call  to get the map product INSEASON_LAI please?

**Comment by Samweli** [comment]
> This feature is available for all region.

noted @LNhas 


> Would it be possible to used the image id from the coverage call to get the map product INSEASON_LAI please?

sorry, I haven't quite get you here @LNhas, do you mean we should change the screenshot?

**Comment by LNArtus** [comment]
No worries @Samweli , it's about the endpoint, could you use the image id query parameter and not the image date? 
like this: 

curl --location --request GET 'http://api-pp.geosys-na.net/field-level-maps/v4/season-fields/e9yr2pm/coverage/{{image_id}}/base-reference-map/INSEASON_LAI' \

This information is available on the body response and when you call the catalog-imagery (new coverage end point) end point like this : 

Exemple on production platform : 
**GET**  http://api.geosys-na.net/field-level-maps/v4/season-fields/e9nwzlv/catalog-imagery

Example of body response : 

[
    {
        "coverageType": "NO_DATA",
        **"image": {
            "id": "IKc73hpUQ6tRWJhB5n9c6ve0Uz3E7i49cinuktK0W4C",**
            "availableBands": [
                "Nir",
                "Red",
                "Blue",
                "Green"
            ],
            "sensor": "SENTINEL_2",
            "soilMaterial": "BARE",
            "spatialResolution": 10.0,
            "weather": "HOT",
            "zenithAngleInDegree": 10.3334942,
            "date": "2022-01-16"
        },
        "maps": [
            {
                "type": "INSEASONPARTIAL_NDVI"
            },
            {
                "type": "INSEASONPARTIAL_EVI"
            }
        ],
        "seasonField": {
            "id": "e9nwzlv",
            "customerExternalId": null
        }
    },

**Comment by LNArtus** [comment]
@Samweli, To be precise, this parameter must be privileged for all map products creation. The use of the image id query parameter instead of image date improves the performance of our API calls.

**Comment by Samweli** [comment]
> @Samweli, To be precise, this parameter must be privileged for all map products creation. The use of the image id query parameter instead of image date improves the performance of our API calls.

alright, thanks @LNhas.
