### ISSUE TITLE
Update API URLs endpoints

### ISSUE THREAD

**Issue by Samweli** [earthdaily/qgis-plugin#127]
Change the API URLs endpoints that the plugin currently uses to the new API URLs.
The URLs mapping should be as noted below

```
IDENTITY_URLS = {   

'na': {
        'test': 'https://identity.preprod.geosys-na.com/v2.1',
        'prod': 'https://identity.geosys-na.com/v2.1'

    },
    'eu': {
        'test': 'https://identity.preprod.geosys-na.com/v2.1'
        'prod': 'https://identity.geosys-eu.com/v2.1'
    }
}
GEOSYS_API_URLS = {
    'na': {
        'test': 'http://api-pp.geosys-na.net',

        'prod': 'http://api.geosys-na.net'
    },
    'eu': {
        'test': 'http://api-pp.geosys-na.net',
        'prod': 'http://api.geosys-eu.net'
    }
}
```

After the update has been made, we need to confirm that the plugin can perform its functionalities that depend on the API and if not we should report all of the missing or incomplete features.

**Comment by Samweli** [comment]
Update the API URLs should be as follows, note the `eu` identity test url has changed

```
IDENTITY_URLS = {   

'na': {
        'test': 'https://identity.preprod.geosys-na.com/v2.1',
        'prod': 'https://identity.geosys-na.com/v2.1'

    },
    'eu': {
        'test': 'https://identity.preprod.geosys-eu.com/v2.1'
        'prod': 'https://identity.geosys-eu.com/v2.1'
    }
}
GEOSYS_API_URLS = {
    'na': {
        'test': 'http://api-pp.geosys-na.net',

        'prod': 'http://api.geosys-na.net'
    },
    'eu': {
        'test': 'http://api-pp.geosys-na.net',
        'prod': 'http://api.geosys-eu.net'
    }
}
```

**Comment by Samweli** [comment]
Updated APIs URL to use https and changed the  `eu` testing URL
```
IDENTITY_URLS = {   

'na': {
        'test': 'https://identity.preprod.geosys-na.com/v2.1',
        'prod': 'https://identity.geosys-na.com/v2.1'

    },
    'eu': {
        'test': 'https://identity.preprod.geosys-eu.com/v2.1'
        'prod': 'https://identity.geosys-eu.com/v2.1'
    }
}
GEOSYS_API_URLS = {
    'na': {
        'test': 'https://api-pp.geosys-na.net',

        'prod': 'https://api.geosys-na.net'
    },
    'eu': {
        'test': 'https://api-pp.geosys-eu.net',
        'prod': 'https://api.geosys-eu.net'
    }
} 
```

**Comment by LNArtus** [comment]
Hi @Samweli , 
There is no testing platform in Europe. Only for the US. So the URLs are : 

IDENTITY_URLS = {   

'na': {
        'test': 'https://identity.preprod.geosys-na.com/v2.1',
        'prod': 'https://identity.geosys-na.com/v2.1'

    },
    'eu': {
        'test': 'https://identity.preprod.geosys-na.com/v2.1'
        'prod': 'https://identity.geosys-eu.com/v2.1'
    }
}
GEOSYS_API_URLS = {
    'na': {
        'test': 'https://api-pp.geosys-na.net',

        'prod': 'https://api.geosys-na.net'
    },
    'eu': {
        'test': 'https://api-pp.geosys-na.net',
        'prod': 'https://api.geosys-eu.net'
    }
}

**Comment by Samweli** [comment]
> Hi @Samweli , There is no testing platform in Europe. Only for the US. So the URLs are :
>

Right thanks @LNArtus
