### ISSUE TITLE
Update description available on the plugin option menu

### ISSUE THREAD

**Issue by Samweli** [earthdaily/qgis-plugin#133]
The current description in the option menu needs to be changed to include a new website URL [ https://earthdailyagro.com/geosys-api/]( https://earthdailyagro.com/geosys-api/) and replace the old one which points to [https://www.geosys.com/bridge/](https://www.geosys.com/bridge/).

A new button labeled `About` should be added in the option menu and it should open a dialog that shows following social media links

```
- EarthDaily agro https://earthdailyagro.com/
- News https://earthdailyagro.com/news/
- Careers https://earthdailyagro.com/careers/
- Contact https://earthdailyagro.com/contact/ 
- Twitter - https://twitter.com/EarthDailyAgro
- Linkedin - https://www.linkedin.com/company/115836/admin/
- Youtube https://www.youtube.com/channel/UCy4X-hM2xRK3oyC_xYKSG_g
```

suggested UI for the social media dialog

![image](https://user-images.githubusercontent.com/2663775/150219624-c056a3ec-b2fe-4e8e-be4f-6d89c1b87bba.png)

**Comment by vermeulendivan** [comment]
Only these links are required. Don't include news, careers and contact
- https://earthdailyagro.com/
- https://earthdaily.com/
- https://twitter.com/EarthDailyAgro
- https://www.linkedin.com/company/115836/admin/
- https://www.youtube.com/channel/UCy4X-hM2xRK3oyC_xYKSG_g
