### ISSUE TITLE
Document new features added

### ISSUE THREAD

**Issue by Samweli** [earthdaily/qgis-plugin#134]
The plugin help panel should be updated to contain description about the new features that are to be added.
The new description should cover the new map product types, their usage and criteria they put upon the parameters, also the link to the developer portal should be included in the description [https://geosys.stoplight.io/auth/email/login](https://geosys.stoplight.io/auth/email/login)

Map product types details
```
“INSEASON_LAI” - Provides the in-season LAI Index. It is used as an indicator of the amount of leaf material.
“REFLECTANCE” - Provides the Reflectance map at Top of Canopy for Sentinel 2 and Lansat-8.
“SOIL” - Provides the in-season Soil type map. Can be generate only in the USA, contains information about soil as collected by the National Cooperative Soil Survey.
“INSEASON_S2REP” - Provides the in-season S2REP Index. Generates a map according to the amount of chlorophyll content per unit of leaf (LCC).
“INSEASON_AVERAGE_NDVI” - Provides the input map and the variable-rate application map based on NDVI map to better inform input placement.
“INSEASON_AVERAGE _LAI” - Provides the input map and the variable-rate application map based on LAI map to better inform input placement.
“INSEASON_AVERAGE_REVERSE_NDVI” - Provides the input map and the variable-rate application map based on NDVI map to better inform input placement.
“INSEASON_AVERAGE_REVERSE_LAI”- Provides the input map and the variable-rate application map based on LAI map to better inform input placement.
“INSEASON_CVIN” - Provides the in-season Chlorophyll Vegetation Index normalized.
```

Sensor type details

```
- DEIMOS-1 - Commercial data at 22 m ground resolution with an approximate 2-day revisit (combined).
- ALSAT-1B – Algeria Satellite -1B with a spatial resolution at 24 m ground resolution, up to 3 days of revisit.  
- GAOFEN_1_WFV1 and GAOFEN -6 WFV, have respectively a ground resolution equal to 8 meters and 16 meters with a revisited equal to 4 days.
- CBERS-4 (MUXCam) - The China-Brazil Earth Resources Satellite Program with 20 meters spatial resolution and a revisit capacity of 26 days. Images are available only in Brazil via the Geosys virtual constellation.
- LANDSAT_8 - Providing moderate-resolution imagery at 30 meters resampled to 15 meters by Geosys. Revisiting every 16 days.
- RESOURCESAT2 - The Linear Imaging Self-Scanning Sensor (LISS-III) with 23.5-meter spatial resolution LISS-IV Camera with 5.8-meter spatial resolution. Revisiting every 24 days.
- SENTINEL_2 - Spatial resolution of 10 m, 20 m and 60 m. Revisiting every 5 days under the same viewing angles. At high latitudes, Sentinel-2 swath overlap, and some regions will be observed twice or more every 5 days, but with different viewing angles. Multi-spectral data with 13 bands in the visible, near infrared, and short-wave infrared part of the spectrum.
```

Screenshot of the requested changes in the help dialog
![image](https://user-images.githubusercontent.com/2663775/150299806-5134513d-4e18-43ef-8834-264fdc0c4c50.png)

**Comment by LNArtus** [comment]
Hi @Samweli here is the last description for the sensor type part: 

•	DEIMOS-1 - Commercial data at 22 m ground resolution with an approximate 2-day revisit (combined).
•	ALSAT-1B – Algeria Satellite -1B with a spatial resolution at 24 m ground resolution, up to 3 days of revisit.  
•	GAOFEN-1 and GAOFEN -6, have respectively a ground resolution equal to 16 meters with a revisited equal to 4 days.
•	CBERS-4 (MUXCam) - The China-Brazil Earth Resources Satellite Program with 20 meters spatial resolution and a revisit capacity of 26 days. Images are available only in Brazil via the Geosys virtual constellation.
•	LANDSAT_8 and LANDSAT_9 - Providing moderate-resolution imagery at 30 meters resampled to 15 meters by Geosys. Revisiting every 16 days.
•	RESOURCESAT2 - The Linear Imaging Self-Scanning Sensor (LISS-III) with 23.5-meter spatial resolution LISS-IV Camera with 5.8-meter spatial resolution. Revisiting every 24 days.
•	SENTINEL_2 - Spatial resolution of 10 m. Revisiting every 5 days under the same viewing angles. Multi-spectral data with 13 bands in the visible, near infrared, and short-wave infrared part of the spectrum.

**Comment by Samweli** [comment]
Thanks, noted @LNArtus
