### ISSUE TITLE
Implement support for gain and offset for brm and model maps

### ISSUE THREAD

**Issue by Samweli** [earthdaily/qgis-plugin#137]
Add gain and offset options in the last parameter panel when the selected map product type was from the below list

  ```
    INSEASON_NDVI
    INSEASON_EVI
    INSEASON_CVI
    INSEASON_CVIN
    INSEASON_GNDVI
    INSEASONPARTIAL_NDVI
    INSEASONPARTIAL_EVI
    INSEASON_LAI
    INSEASON_S2REP
    INSEASON_AVERAGE_NDVI 
    INSEASON_AVERAGE _LAI 
    INSEASON_AVERAGE_REVERSE_NDVI 
    INSEASON_AVERAGE_REVERSE_LAI 
```
Example request for fetching gain/offset options
```
curl --location --request \
GET 'https://api-pp.geosys-na.net:443/field-level-maps/v4/season-fields/e9ywp1n/coverage/{{image.id}}/base-reference-map/INSEASON_EVI/image.png?gain=1.5&legendType=fixed' \
--header 'Authorization: Bearer **Replace with token**'
```

Screenshot of location where the new options should be added
![image](https://user-images.githubusercontent.com/2663775/150326875-bd90ba13-30cf-4496-9652-5767bfcae6a4.png)

**Comment by vermeulendivan** [comment]
Map products to NOT include:
COLORCOMPOSITION
ELEVATION
OM
SAMZ
YGM
YPM

**Comment by vermeulendivan** [comment]
@Samweli At the moment I've included the REFLECTANCE map product type as having the gain/offset settings available, should that be the case? Also, assuming SOIL map should not be included?  Both cases are newly added product options.
