### ISSUE TITLE
Issue with the Elevation map type

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#159]
**Bug description**

When I choose the Elevation map type, I am redirectly on the Geosys plug-in settings dock. I have to click on the Back button to see all the maps.
The maps that appear are not elevation maps, but appear to be NDVI partial maps or other indexed maps.

**To Reproduce**
Create a field on the US area
Connect on our preproduction platform 
Select a field
Choose a map type equal to Elevation
Click on the search buton

Elevation maps example : 
![image](https://user-images.githubusercontent.com/69202500/154455993-873a13ae-b735-4b7d-8042-8554bc0746a2.png)

What the user see : 
![image](https://user-images.githubusercontent.com/69202500/154456729-57baed2e-c7a1-4a1c-8bc6-b74adb6a4f17.png)
![image](https://user-images.githubusercontent.com/69202500/154456767-de44a61b-d63d-421c-9d4a-27e560586c92.png)

**Expected behavior**

Given that the user is on the Coverage Parameters panel, when choosing a map product type equal to Elevation then they shall be able to see all Elevation maps on the Map Parameters Panel

**Comment by vermeulendivan** [comment]
The plugin has originally been set up to not provide the user with templates for the elevation, and rather skip directly to the map creation section. This makes sense as there are likely only one elevation source available and sensors such as S2, L8 etc does not provide elevation. 
See code section on this.

![image (2)](https://user-images.githubusercontent.com/79740955/154972880-7d49673d-d7e1-48b0-9272-8ad44ac78adf.png)
