### ISSUE TITLE
The S2rep map is not working  (PEU)

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#174]
**Describe the bug**
No coverage on the production Europe to create S2rep map.

**To Reproduce**
1. Go to the geosys Plug-in 
![image](https://user-images.githubusercontent.com/69202500/155693583-7e20c30a-31d2-4b2a-abc9-a1e984187a3d.png)

(before connect to the production europe platform
2.  choose S2rep map type

**Expected behavior**
when the user chosse to create a S2rep map they should be able to see all S2rep map on the coverage windows

**Comment by LNArtus** [comment]
Hi @vermeulendivan S2Rep is a new indexe and it's available with the catalog imagery API or Coverage API (Coverage API, old way or new way whenever) and the map type is : "maps": [
{
"type": "INSEASON_S2REP"
}

But this feature is just available in our europe production platform, so if you call the API on our testing platform maybe you will not see the map type S2rep, that does not mean is not a option, just it's mean that you cannot create the S2rep index map with your field test.

**Comment by vermeulendivan** [comment]
Hi @LNArtus . Also noted your comments from https://github.com/GEOSYS/qgis-plugin/issues/170 related to this. Will be having a look shortly. And you are correct, I've been looking at US not EU - apologies, my mistake. Just want to mention we are using the correct maps.type key as you posted above.
