### ISSUE TITLE
Cannot get more than one hotspot layer 

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#175]
**Describe the bug**

When we have chosen to create a hotspot, and we have clicked on fetch hotspot and on the Hot spot option, we are not able to redo the previous steps to display a second HotSpot layer

**To Reproduce**
1. Go to the geosys Plugin center
![image](https://user-images.githubusercontent.com/69202500/155698913-00d8d66a-af0e-464e-8e65-38c557f0f841.png)

3. Click on fecth HotSpots 
4. Click on HotSpots foe each polygon
5. Click on Minimum 
6. See the HotSpot layer => OK 
7. Click on Fecth HotSpot
8. 
![image](https://user-images.githubusercontent.com/69202500/155699355-a1861806-7dc9-48ab-92d4-e5a97d2e54ed.png)

9. Click on HotSpot for each polygon part 
10. Click on Maximum 
11. No layer add to the Layer panel ....
![image](https://user-images.githubusercontent.com/69202500/155699423-e1f70b96-8fc7-482a-8514-5e84b12e9e3c.png)

**Expected behavior**
The user should be able to create more than one layer Hotspot and see difference between hotSpot layer.

**Comment by vermeulendivan** [comment]
This has been resolved by https://github.com/GEOSYS/qgis-plugin/pull/178
