### ISSUE TITLE
Cannot create CVIN map on PUS (PEU ok)

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#176]
**Describe the bug**
We cannot create CVIN on the production Europe while on the production US yes

**Comment by LNArtus** [comment]
Hi @vermeulendivan , this one not works on the plug-in side. 
When I selct a field on europe, and after connecting to the europe production platform. I cannot see anything on the coverage panel center.

here is the curl of the request on Postman side : 

curl --location --request POST 'http://api.geosys-eu.net/field-level-maps/v4/catalog-imagery?Image.Date=$gte:2022-01-01&maps.type=INSEASON_CVIN' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcyOTgxOEM2QzYwOTkzRkM2MTc1NTRENUVFNTg1N0QzRUQ1M0MxQ0FSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6ImNwZ1l4c1lKa194aGRWVFY3bGhYMC0xVHdjbyJ9.eyJuYmYiOjE2NDc1MzY0NDEsImV4cCI6MTY0NzU0MDA0MSwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtZXUuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1ldS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJtYXBwcm9kdWN0X2FwaSIsInN1YiI6IjEwMDAyMzcyMyIsImF1dGhfdGltZSI6MTY0NzUzNjQ0MSwiaWRwIjoibG9jYWwiLCJnZW82X3N1YiI6IjFDV1NSZUYyVnhrck9uaUhTMDZtYXUiLCJpYXQiOjE2NDc1MzY0NDEsInNjb3BlIjpbImdlbzY6YnJpZGdlIiwib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInBhc3N3b3JkIl19.g7gv6KYQGEdKCKgGvPiGbHDe6lDb1mg7ftD_migjmAQZ-3DXiW_HHp8YtoxUvKCF5TmyrK9fawWHVO4wxKsJRQlG2f0FKGHLuCnon2wRMLn-xSc9ai3MwTuD83C1cPsjaoqBzEvMOEWjoLV8o5pEw4P6HtAkzcQiveBL_KlbtzaAV74WDTQWxe5lpAeP_KQAyWkGmkUO5YIr21g0stjGgWfdAG0BR9NA4BxeESphfVC60bk-UcBvwhrlV6fPyOu0u6V9oEY5W7cxrcPsat149McLk0DPUOFXEfY966NgQmZ38h758ktwr0vaRM0KV9HR5qRR1cYeHuQhUUmru6a2XA' \
--data-raw '{
  "Geometry": "MultiPolygon (((1.66884653867381183 43.59019247857889923, 1.67026680245843262 43.5900335001322361, 1.67058958968221005 43.59034210496863437, 1.67336555980669632 43.5900896102201898, 1.67430809850012619 43.5883595251166156, 1.6738820193647399 43.58817248591049776, 1.67384328489788659 43.58797609411855944, 1.67393366532054433 43.58789192601156515, 1.66882071569590962 43.58517977956837086, 1.66836881358262112 43.58585315146790151, 1.66847210549422997 43.5871811684148156, 1.66894983058542024 43.58712505561552319, 1.66940173269870917 43.58694736473934483, 1.66977616587829081 43.58674161675371295, 1.66987945778989966 43.586788377721291, 1.66942755567661116 43.58705023846843574, 1.67029262543633461 43.58763942098442357, 1.66862704336164325 43.58866813853602906, 1.66884653867381183 43.59019247857889923)))",
  "Crop": {
    "Id": "CORN"
  },
  "SowingDate": "2022-01-01"
}'

Could you please verify ?

**Comment by vermeulendivan** [comment]
@LNArtus It works fine for me for the EU are:
![image](https://user-images.githubusercontent.com/79740955/158966049-09e9b270-674a-47a8-8e87-8307b1ebb3b7.png)

For US it does not work for me. Strange that because based on your first comment its the other way around.
The best I think will be to change this case to the catalog-imagery as well.

**Comment by LNArtus** [comment]
propably the best way to change by the catalog imagery too.
Are you available today for a quick call @vermeulendivan  ? in the aim to check if all works well

**Comment by vermeulendivan** [comment]
@LNArtus Sure. No problem with me. Will prefer we get all of the important stuff done today as I won't be available until the 4th of April again. Between 12h and 13h30 today I'm in another meeting, otherwise I'm available and will be busy with this plugin.
