### ISSUE TITLE
Missing icon on the Geosys plugin option center

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#190]
**Describe the bug**
When the user wants to make changes using the QGIS geosys plugin options panel, he sees the QGIS icon and not the new Geosys plug_in icon. 

**To Reproduce**
1. Go to the Geosys QGIS options panel
2. Scroll down and see on the top of the panel the wrong icon 
3. Scroll down and click on connect and see the wrong icon and wrong API name (Bridge is the old name)

**Expected behavior**
Change the icon by the new one 

**Screenshots**

![plugin_icon_option](https://user-images.githubusercontent.com/69202500/157488954-1cacb833-1f32-4879-b445-e44551e11cd5.png)
![connect_icon](https://user-images.githubusercontent.com/69202500/157489169-542cfbb6-d29e-4d0f-8b41-be29d2977004.png)

**Comment by vermeulendivan** [comment]
@LNArtus What should the new name be? Basically, to what should "Bridge API" be changed?

**Comment by LNArtus** [comment]
Hi @vermeulendivan the new name is : Geosys API

**Comment by vermeulendivan** [comment]
@LNArtus Thanks for your quick response!
