### ISSUE TITLE
Cannot create CVIN map on both production platforms

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#196]
**Describe the bug**
Cannot create CVIn map on both production platform
**To Reproduce**
1. select a field on the production europe or us 
2. choose the CVIN map type
3. Click on all sensor type
4. Scroll down and click on the search button
5. See error => no expected map

**Comment by vermeulendivan** [comment]
See https://github.com/GEOSYS/qgis-plugin/issues/176
