### ISSUE TITLE
Bad map display of S2rep map on the coverage panel center

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#197]
**Describe the bug**
When I select the S2rep map and search a result, I cannot see the Thumbail of each result.

**To Reproduce**
1. Go to the parameter panel
2. Choose the map type S2rep
3. Scroll down and click on the search button

**Expected behavior**

**Screenshots**
![S2rep](https://user-images.githubusercontent.com/69202500/158858861-f4c90238-af57-4d40-868c-93fc6242fcdb.png)

**Comment by vermeulendivan** [comment]
@LNArtus This is the same problem I showed you Wednsday night with the nitrogen maps. Requests for the tumbnails results in no error, in fact the api does respond positive but with no thumbnail to download, etc. This is also only an issue with the catalog-imagery cases, no issue with the original coverage approach. Can you maybe send me an example link for catalog-imagery thumbnails?

**Comment by LNArtus** [comment]
**yes, here is the call for on the US production platform, with a POST catalog imagery creation :** 

curl --location --request POST 'http://api.geosys-na.net/field-level-maps/v4/catalog-imagery?Image.Date=$gte:2021-01-01&maps.type=INSEASON_CVIN' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcyOTgxOEM2QzYwOTkzRkM2MTc1NTRENUVFNTg1N0QzRUQ1M0MxQ0FSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6ImNwZ1l4c1lKa194aGRWVFY3bGhYMC0xVHdjbyJ9.eyJuYmYiOjE2NDc1Mzc2NDgsImV4cCI6MTY0NzU0MTI0OCwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtZXUuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1ldS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJtYXBwcm9kdWN0X2FwaSIsInN1YiI6IjEwMDAyMzcyMyIsImF1dGhfdGltZSI6MTY0NzUzNzY0OCwiaWRwIjoibG9jYWwiLCJnZW82X3N1YiI6IjFDV1NSZUYyVnhrck9uaUhTMDZtYXUiLCJpYXQiOjE2NDc1Mzc2NDgsInNjb3BlIjpbImdlbzY6YnJpZGdlIiwib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInBhc3N3b3JkIl19.RceLf8KrqnoWc77djVF4JYzsjZyDJhgPEMVeIQLl3KQDaZAFxLa8x7xauCHDzKCT3n8IEo3Iqw-LQmhZeAwWKUKx240rMXrcHzalugFuu80-B2YX-aRmiYw6d0dFVU_KBg-AE_bMJQc6pc0I088ER_h_t2IclLMdIR86lZXEJ52y3MtpH6cPCEnHhvlty8rrMdgLXjE7LcZVPzTdkj2yfPKhKAi4I7lfTYK_AxDKoV5tw4DBOMc7dDYCSzwgVqXblTpl0FeURZI7HvFaOIM96_8ZT06Jk1EW6V3JGL-YPNO0IIYQPJ40Pw-4kNeHzPJ3bUaZNkQN1RQeTZmwX3NvMA' \
--data-raw '{
  "Geometry": "MultiPolygon (((-94.64445673926874747 43.74670608953211826, -94.63447391619469329 43.74672755270827196, -94.63447391619469329 43.73610233957576554, -94.63601887690855108 43.73616674048638941, -94.63554350438121787 43.73640287656610326, -94.6354543720323278 43.73655314449563747, -94.63587032299373902 43.73700394602165886, -94.63747470527350458 43.73685367922341527, -94.6372073082268912 43.73599500457081035, -94.63607829847445885 43.73590913642832589, -94.63604858769150496 43.73599500457081035, -94.63450362697766138 43.73597353754672667, -94.63453333776061527 43.73238843656938712, -94.64457558240057722 43.73240990487865787, -94.64442702848579358 43.74666316315671821, -94.64445673926874747 43.74670608953211826)))",
  "Crop": {
    "Id": "CORN"
  },
  "SowingDate": "2021-01-01"
}'





**And the result with a the GET :** 

curl --location --request GET 'http://api.geosys-na.net/field-level-maps/v4/season-fields/7e9rdbm/coverage/IKc73hpUQ6tw8bHTTXPDSsU4G1y0oaWbhlpCSU7Mty0/base-reference-map/INSEASON_CVI/image.png' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJDQzMxQzZDOUI5RUM5NUZDQkQ1M0Y3RjVDQjhDQzI1QzA4Mjk5RjlSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6IkxNTWNiSnVleVZfTDFUOV9YTGpNSmNDQ21mayJ9.eyJuYmYiOjE2NDc1OTQwNDcsImV4cCI6MTY0NzU5NzY0NywiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtbmEuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1uYS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJtYXBwcm9kdWN0X2FwaSIsInN1YiI6IjEwMDEwODkyMiIsImF1dGhfdGltZSI6MTY0NzU5NDA0NywiaWRwIjoibG9jYWwiLCJnZW82X3N1YiI6IjF0bUl4T3RENUQ1MWFvRXpLT2JyMlkiLCJpYXQiOjE2NDc1OTQwNDcsInNjb3BlIjpbImdlbzY6YnJpZGdlIiwib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInBhc3N3b3JkIl19.Y6p3Yv3WK9PhTSGY2d5rhXCZ98MW2Qs9Cd1ZNvxA291sVMXpv4V_gL1WQeNT3Udke6c6keV2ubaayyuPkQeJX4Jhp7DXtEPW1dKxiZD9DE2S5JCBGEGTO5zpq_iVI11utt-F5AWKCsRix2LWyLQ3JZU3giCzVJvt5Sdrl9aYa2IAk4sMQ4aBHYqecvDxdVgQwexXiT0Byx5vjOtKCkDvKNAwQRPc9R-cpCJ3me35li7agpWjoU_MAYOvbA8yFo0Mcl-jUFTPPqI78rrCyhK_yy81e2PEQKKsKBDPvKk3xq5ZZ_X_FiHntYwLhh3hvPAdYzEEonplil0oVZirNgnvYQ'




**On the Production Europe here is the POST catalog imagery request :** 

curl --location --request POST 'http://api.geosys-eu.net/field-level-maps/v4/catalog-imagery?Image.Date=$gte:2022-01-01&maps.type=INSEASON_CVIN' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcyOTgxOEM2QzYwOTkzRkM2MTc1NTRENUVFNTg1N0QzRUQ1M0MxQ0FSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6ImNwZ1l4c1lKa194aGRWVFY3bGhYMC0xVHdjbyJ9.eyJuYmYiOjE2NDc1OTQyNDMsImV4cCI6MTY0NzU5Nzg0MywiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtZXUuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1ldS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJtYXBwcm9kdWN0X2FwaSIsInN1YiI6IjEwMDAyMzcyMyIsImF1dGhfdGltZSI6MTY0NzU5NDI0MywiaWRwIjoibG9jYWwiLCJnZW82X3N1YiI6IjFDV1NSZUYyVnhrck9uaUhTMDZtYXUiLCJpYXQiOjE2NDc1OTQyNDMsInNjb3BlIjpbImdlbzY6YnJpZGdlIiwib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInBhc3N3b3JkIl19.IUIQtnzu5k_YUFzZjFCges07nW0fgFj2_jD3XxFHM5KT3C56niovDnj0dSdguKXGOhrguki1AGJ7bs_e1msVrs_E-1CBHfzlY96KgB_yHa3xL2GMCm8ZxHPgFWJm-t1ihZEWeEKgHCEwdpfwpSabqmTNI8AC0ONFPT-ZX38RM9iyrgkXr6s8H-KdaSjLp0ovkOa2FaYije-rEU0jAOIfMZWufvqcPeVLwi8KR5zUUkz4WiGab20lBsIzj4fKGdEcQpzUzm_5VNLu4G3A20FHgYg6JM148djC6yfbP-CORL9hBaKkO6z7lt5LwILSvzxVI8dBo1Ib6lEYq7wt5oGrxQ' \
--data-raw '{
  "Geometry": "MultiPolygon (((1.66884653867381183 43.59019247857889923, 1.67026680245843262 43.5900335001322361, 1.67058958968221005 43.59034210496863437, 1.67336555980669632 43.5900896102201898, 1.67430809850012619 43.5883595251166156, 1.6738820193647399 43.58817248591049776, 1.67384328489788659 43.58797609411855944, 1.67393366532054433 43.58789192601156515, 1.66882071569590962 43.58517977956837086, 1.66836881358262112 43.58585315146790151, 1.66847210549422997 43.5871811684148156, 1.66894983058542024 43.58712505561552319, 1.66940173269870917 43.58694736473934483, 1.66977616587829081 43.58674161675371295, 1.66987945778989966 43.586788377721291, 1.66942755567661116 43.58705023846843574, 1.67029262543633461 43.58763942098442357, 1.66862704336164325 43.58866813853602906, 1.66884653867381183 43.59019247857889923)))",
  "Crop": {
    "Id": "CORN"
  },
  "SowingDate": "2022-01-01"
}'





**And the request to create the map with the Get method :** 


curl --location --request GET 'http://api.geosys-eu.net/field-level-maps/v4/season-fields/ezb973n/coverage/IKc73hpUQ6tsJbTOee1A28t8ZK3bJoAJvnyeN9npk2O/base-reference-map/INSEASON_CVI/image.png' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcyOTgxOEM2QzYwOTkzRkM2MTc1NTRENUVFNTg1N0QzRUQ1M0MxQ0FSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6ImNwZ1l4c1lKa194aGRWVFY3bGhYMC0xVHdjbyJ9.eyJuYmYiOjE2NDc1OTQyNDMsImV4cCI6MTY0NzU5Nzg0MywiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtZXUuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1ldS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJtYXBwcm9kdWN0X2FwaSIsInN1YiI6IjEwMDAyMzcyMyIsImF1dGhfdGltZSI6MTY0NzU5NDI0MywiaWRwIjoibG9jYWwiLCJnZW82X3N1YiI6IjFDV1NSZUYyVnhrck9uaUhTMDZtYXUiLCJpYXQiOjE2NDc1OTQyNDMsInNjb3BlIjpbImdlbzY6YnJpZGdlIiwib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInBhc3N3b3JkIl19.IUIQtnzu5k_YUFzZjFCges07nW0fgFj2_jD3XxFHM5KT3C56niovDnj0dSdguKXGOhrguki1AGJ7bs_e1msVrs_E-1CBHfzlY96KgB_yHa3xL2GMCm8ZxHPgFWJm-t1ihZEWeEKgHCEwdpfwpSabqmTNI8AC0ONFPT-ZX38RM9iyrgkXr6s8H-KdaSjLp0ovkOa2FaYije-rEU0jAOIfMZWufvqcPeVLwi8KR5zUUkz4WiGab20lBsIzj4fKGdEcQpzUzm_5VNLu4G3A20FHgYg6JM148djC6yfbP-CORL9hBaKkO6z7lt5LwILSvzxVI8dBo1Ib6lEYq7wt5oGrxQ'

**Comment by LNArtus** [comment]
**POST catalog imagery creation for a field on the europe platform :** 

curl --location --request POST 'http://api.geosys-eu.net/field-level-maps/v4/catalog-imagery?Image.Date=$gte:2022-01-01&maps.type=INSEASON_CVIN' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcyOTgxOEM2QzYwOTkzRkM2MTc1NTRENUVFNTg1N0QzRUQ1M0MxQ0FSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6ImNwZ1l4c1lKa194aGRWVFY3bGhYMC0xVHdjbyJ9.eyJuYmYiOjE2NDc1OTQyNDMsImV4cCI6MTY0NzU5Nzg0MywiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtZXUuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1ldS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJtYXBwcm9kdWN0X2FwaSIsInN1YiI6IjEwMDAyMzcyMyIsImF1dGhfdGltZSI6MTY0NzU5NDI0MywiaWRwIjoibG9jYWwiLCJnZW82X3N1YiI6IjFDV1NSZUYyVnhrck9uaUhTMDZtYXUiLCJpYXQiOjE2NDc1OTQyNDMsInNjb3BlIjpbImdlbzY6YnJpZGdlIiwib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInBhc3N3b3JkIl19.IUIQtnzu5k_YUFzZjFCges07nW0fgFj2_jD3XxFHM5KT3C56niovDnj0dSdguKXGOhrguki1AGJ7bs_e1msVrs_E-1CBHfzlY96KgB_yHa3xL2GMCm8ZxHPgFWJm-t1ihZEWeEKgHCEwdpfwpSabqmTNI8AC0ONFPT-ZX38RM9iyrgkXr6s8H-KdaSjLp0ovkOa2FaYije-rEU0jAOIfMZWufvqcPeVLwi8KR5zUUkz4WiGab20lBsIzj4fKGdEcQpzUzm_5VNLu4G3A20FHgYg6JM148djC6yfbP-CORL9hBaKkO6z7lt5LwILSvzxVI8dBo1Ib6lEYq7wt5oGrxQ' \
--data-raw '{
  "Geometry": "MultiPolygon (((1.66884653867381183 43.59019247857889923, 1.67026680245843262 43.5900335001322361, 1.67058958968221005 43.59034210496863437, 1.67336555980669632 43.5900896102201898, 1.67430809850012619 43.5883595251166156, 1.6738820193647399 43.58817248591049776, 1.67384328489788659 43.58797609411855944, 1.67393366532054433 43.58789192601156515, 1.66882071569590962 43.58517977956837086, 1.66836881358262112 43.58585315146790151, 1.66847210549422997 43.5871811684148156, 1.66894983058542024 43.58712505561552319, 1.66940173269870917 43.58694736473934483, 1.66977616587829081 43.58674161675371295, 1.66987945778989966 43.586788377721291, 1.66942755567661116 43.58705023846843574, 1.67029262543633461 43.58763942098442357, 1.66862704336164325 43.58866813853602906, 1.66884653867381183 43.59019247857889923)))",
  "Crop": {
    "Id": "CORN"
  },
  "SowingDate": "2022-01-01"
}'




**Get request to create the CVIn map on the Europe production :** 

curl --location --request GET 'http://api.geosys-eu.net/field-level-maps/v4/season-fields/ezb973n/coverage/IKc73hpUQ6tsJbTOee1A28t8ZK3bJoAJvnyeN9npk2O/base-reference-map/INSEASON_CVIN/thumbnail.png' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcyOTgxOEM2QzYwOTkzRkM2MTc1NTRENUVFNTg1N0QzRUQ1M0MxQ0FSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6ImNwZ1l4c1lKa194aGRWVFY3bGhYMC0xVHdjbyJ9.eyJuYmYiOjE2NDc1OTQ2NTEsImV4cCI6MTY0NzU5ODI1MSwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtZXUuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1ldS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJtYXBwcm9kdWN0X2FwaSIsInN1YiI6IjEwMDAyMzcyMyIsImF1dGhfdGltZSI6MTY0NzU5NDY1MSwiaWRwIjoibG9jYWwiLCJnZW82X3N1YiI6IjFDV1NSZUYyVnhrck9uaUhTMDZtYXUiLCJpYXQiOjE2NDc1OTQ2NTEsInNjb3BlIjpbImdlbzY6YnJpZGdlIiwib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInBhc3N3b3JkIl19.CmXeG3KHw90idqKg9B-gr9rpq-6IN-8ZMX78esnv6vbh8mfCoWIRXvueFgscSncNu5v-IO6vMVt0VbS-_6ikwxC36GsXGinbYTeL4228bydTCWyNaxtAYkk3AKXyUnY8GBvW7fNE-auFLmLErO-LJsbVuOpuG5YWoZ2B_Z5JJdmIQKsVF02SZJeVW4zfY2IBJ-WbQC9byfHa2o-BDAi8e-CBPG28fwDJcqcVRyCY-YUG3uQcZR9g3SiEvVufFk9FLLq6xGYlR-sz5kulX9rT1oI4GV-lRdI2ycfBNXGT7fwq5Qcy0-_X-B-8AU4kJRorfnbIynrD4Bto60ymWZZ8sg'

With a

**Comment by LNArtus** [comment]
**POST creation for a field on the US production platform :** 

curl --location --request POST 'http://api.geosys-na.net/field-level-maps/v4/catalog-imagery?Image.Date=$gte:2021-01-01&maps.type=INSEASON_CVIN' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJDQzMxQzZDOUI5RUM5NUZDQkQ1M0Y3RjVDQjhDQzI1QzA4Mjk5RjlSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6IkxNTWNiSnVleVZfTDFUOV9YTGpNSmNDQ21mayJ9.eyJuYmYiOjE2NDc1OTQ4MjMsImV4cCI6MTY0NzU5ODQyMywiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtbmEuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1uYS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJtYXBwcm9kdWN0X2FwaSIsInN1YiI6IjEwMDEwODkyMiIsImF1dGhfdGltZSI6MTY0NzU5NDgyMywiaWRwIjoibG9jYWwiLCJnZW82X3N1YiI6IjF0bUl4T3RENUQ1MWFvRXpLT2JyMlkiLCJpYXQiOjE2NDc1OTQ4MjMsInNjb3BlIjpbImdlbzY6YnJpZGdlIiwib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInBhc3N3b3JkIl19.Yxq-Na1Xcbld8m83ZmLlVpW-SI8m4oOUqvRyiAN0u7rkPJ6uBIk5i17b6tjMVTFoVy37yeUiwDB1PUiGjQr0wQYYP9Xpurj8pM0Oe89G6j7KXdBf6hT4O6bJ1PubTHiOCfkhzJH4KFK4LzA0OegHB_o9tMwz7oeQMru1vV37IghprIZm3CtPMYnn-cGaV7BmL8a1eIGkjLg6tov8MEpiZVNHFnBKi5Zp8CdetGw8yVSDsS2a3VQn1gschajGnKh88tbXTxj01jR_Tb3LiJGTYw5YKLIUHMBjd-OPd7C2A4Blffy0GKI1yPbBPap4cFRieMm2EnB_CbxBstdqYt-Szg' \
--data-raw '{
  "Geometry": "MultiPolygon (((-94.64445673926874747 43.74670608953211826, -94.63447391619469329 43.74672755270827196, -94.63447391619469329 43.73610233957576554, -94.63601887690855108 43.73616674048638941, -94.63554350438121787 43.73640287656610326, -94.6354543720323278 43.73655314449563747, -94.63587032299373902 43.73700394602165886, -94.63747470527350458 43.73685367922341527, -94.6372073082268912 43.73599500457081035, -94.63607829847445885 43.73590913642832589, -94.63604858769150496 43.73599500457081035, -94.63450362697766138 43.73597353754672667, -94.63453333776061527 43.73238843656938712, -94.64457558240057722 43.73240990487865787, -94.64442702848579358 43.74666316315671821, -94.64445673926874747 43.74670608953211826)))",
  "Crop": {
    "Id": "CORN"
  },
  "SowingDate": "2022-01-01"
}'


**GET request to create the CVIN map :** 

curl --location --request GET 'http://api.geosys-na.net/field-level-maps/v4/season-fields/7e9rdbm/coverage/IKc73hpUQ6tw8bHTTXPDSsU4G1y0oaWbhlpCSU7Mty0/base-reference-map/INSEASON_CVIN/thumbnail.png' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJDQzMxQzZDOUI5RUM5NUZDQkQ1M0Y3RjVDQjhDQzI1QzA4Mjk5RjlSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6IkxNTWNiSnVleVZfTDFUOV9YTGpNSmNDQ21mayJ9.eyJuYmYiOjE2NDc1OTQ4MjMsImV4cCI6MTY0NzU5ODQyMywiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtbmEuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1uYS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJtYXBwcm9kdWN0X2FwaSIsInN1YiI6IjEwMDEwODkyMiIsImF1dGhfdGltZSI6MTY0NzU5NDgyMywiaWRwIjoibG9jYWwiLCJnZW82X3N1YiI6IjF0bUl4T3RENUQ1MWFvRXpLT2JyMlkiLCJpYXQiOjE2NDc1OTQ4MjMsInNjb3BlIjpbImdlbzY6YnJpZGdlIiwib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInBhc3N3b3JkIl19.Yxq-Na1Xcbld8m83ZmLlVpW-SI8m4oOUqvRyiAN0u7rkPJ6uBIk5i17b6tjMVTFoVy37yeUiwDB1PUiGjQr0wQYYP9Xpurj8pM0Oe89G6j7KXdBf6hT4O6bJ1PubTHiOCfkhzJH4KFK4LzA0OegHB_o9tMwz7oeQMru1vV37IghprIZm3CtPMYnn-cGaV7BmL8a1eIGkjLg6tov8MEpiZVNHFnBKi5Zp8CdetGw8yVSDsS2a3VQn1gschajGnKh88tbXTxj01jR_Tb3LiJGTYw5YKLIUHMBjd-OPd7C2A4Blffy0GKI1yPbBPap4cFRieMm2EnB_CbxBstdqYt-Szg'

**Comment by vermeulendivan** [comment]
@LNArtus These links should be part of https://github.com/GEOSYS/qgis-plugin/issues/176 and is not related to thumbnails.

**Comment by LNArtus** [comment]
Yes you alright:) 

**Same for the S2REp map so :** 


curl --location --request POST 'http://api.geosys-eu.net/field-level-maps/v4/catalog-imagery?Image.Date=$gte:2021-01-01&coverageType=CLEAR&Maps.Type=INSEASON_S2REP' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcyOTgxOEM2QzYwOTkzRkM2MTc1NTRENUVFNTg1N0QzRUQ1M0MxQ0FSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6ImNwZ1l4c1lKa194aGRWVFY3bGhYMC0xVHdjbyJ9.eyJuYmYiOjE2NDc1OTUzNDQsImV4cCI6MTY0NzU5ODk0NCwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtZXUuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1ldS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJtYXBwcm9kdWN0X2FwaSIsInN1YiI6IjEwMDAyMzcyMyIsImF1dGhfdGltZSI6MTY0NzU5NTM0NCwiaWRwIjoibG9jYWwiLCJnZW82X3N1YiI6IjFDV1NSZUYyVnhrck9uaUhTMDZtYXUiLCJpYXQiOjE2NDc1OTUzNDQsInNjb3BlIjpbImdlbzY6YnJpZGdlIiwib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInBhc3N3b3JkIl19.Bz7YEhF1tDaOhB8hUnkwCKNIt7V3ApFcg3BfBuhbmrMXY4HDY__u82DS8qNZ4irKcdZaeQIDTdxPCiSDShzgXBU_W5zxN_MwcCQa2qWuyDt7ch2iWC3kSc3k-IOTU1jMmckY34tI1f9om4cD4FPYEjSi9htvsPhCp2c4oMmmHIDSn_qlfNS1qA5zRiQh2YMI6bxTeJoCg6Vm7FS1Ot08ylCNQOJAgd_bLXpkIezgDCd4GcIEn47PyXPgBnPuGr-OfwO1h305yyRCV_zVOYes5-QIjnvAF87o_4-PYUds1Hwvaaudab9Yt8kni1Hjq7Tsk41gY9tELbSg00PZYxWmcQ' \
--data-raw '
{
  "Geometry": "Polygon ((4.50246733833568502 46.38435529802691093, 4.50199094339217698 46.38383301579256113, 4.50211854918061682 46.38372151669082655, 4.50221212675880533 46.38362175414361133, 4.5027650851753771 46.38343983373525248, 4.50501094705191285 46.38302904348646649, 4.50522362336597837 46.3833928864346916, 4.50587015936073865 46.38334007067329878, 4.50640610367218475 46.38343983373525248, 4.50736740061176189 46.38395038302205364, 4.50677190693237861 46.38430248319659199, 4.50611686388505461 46.38406188165635768, 4.50561494778385985 46.38398559314169489, 4.50478976368528361 46.38405014496873235, 4.50279060633306472 46.38431421982997449, 4.50254390180874786 46.3843905078853993, 4.50246733833568502 46.38435529802691093))",
  "Crop": {
    "Id": "CORN"
  },
  "SowingDate": "2021-09-01T00:00:00"
}'

**Get method to create the thumbail :** 

curl --location --request GET 'http://api.geosys-eu.net/field-level-maps/v4/season-fields/b3zgdex/coverage/IKc73hpUQ6tsJbTOee1A28t8ZK3bJoAH5yWNj10VTcK/base-reference-map/INSEASON_S2REP/thumbnail.png' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcyOTgxOEM2QzYwOTkzRkM2MTc1NTRENUVFNTg1N0QzRUQ1M0MxQ0FSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6ImNwZ1l4c1lKa194aGRWVFY3bGhYMC0xVHdjbyJ9.eyJuYmYiOjE2NDc1OTUzNDQsImV4cCI6MTY0NzU5ODk0NCwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtZXUuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1ldS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJtYXBwcm9kdWN0X2FwaSIsInN1YiI6IjEwMDAyMzcyMyIsImF1dGhfdGltZSI6MTY0NzU5NTM0NCwiaWRwIjoibG9jYWwiLCJnZW82X3N1YiI6IjFDV1NSZUYyVnhrck9uaUhTMDZtYXUiLCJpYXQiOjE2NDc1OTUzNDQsInNjb3BlIjpbImdlbzY6YnJpZGdlIiwib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInBhc3N3b3JkIl19.Bz7YEhF1tDaOhB8hUnkwCKNIt7V3ApFcg3BfBuhbmrMXY4HDY__u82DS8qNZ4irKcdZaeQIDTdxPCiSDShzgXBU_W5zxN_MwcCQa2qWuyDt7ch2iWC3kSc3k-IOTU1jMmckY34tI1f9om4cD4FPYEjSi9htvsPhCp2c4oMmmHIDSn_qlfNS1qA5zRiQh2YMI6bxTeJoCg6Vm7FS1Ot08ylCNQOJAgd_bLXpkIezgDCd4GcIEn47PyXPgBnPuGr-OfwO1h305yyRCV_zVOYes5-QIjnvAF87o_4-PYUds1Hwvaaudab9Yt8kni1Hjq7Tsk41gY9tELbSg00PZYxWmcQ'

**Comment by vermeulendivan** [comment]
@LNArtus Thanks for the thumbnail example! This will help a lot.
