### ISSUE TITLE
EPIC 1.2: Testing Framework & Travis

### ISSUE THREAD

**Issue by AndreLester** [earthdaily/qgis-plugin#20]
**Expectation:** As a product owner, I would like to know that any submissions made to the plugin code
base are subject to automated testing to ensure a good standard of code quality.  

**Acceptance criteria:** Given a new pull request being opened, when a reviewer views the pull
request queue then he should observe the test status of each pull request.

![image](https://user-images.githubusercontent.com/13916357/55160030-0f351b80-516b-11e9-8847-9fb7d770e28e.png)

**Comment by mal147** [comment]
close issue
