### ISSUE TITLE
Nitrogen maps n-planned value

### ISSUE THREAD

**Issue by vermeulendivan** [earthdaily/qgis-plugin#203]
This is part of support.
N-planned parameter should be added to the coverage panel. This is only for nitrogen maps, namely inseasonfield ndvi/lai, inseason average lai/ndvi reverse

![image](https://user-images.githubusercontent.com/79740955/159017032-09e931bb-3345-4971-9b7b-b8729b6315e9.png)

**Comment by vermeulendivan** [comment]
http://api.geosys-eu.net/field-level-maps/v4/season-fields/{{season_field_id_base_nitrogen_map}}/coverage/{{image_id_nitrogen_map}}/model-map/INSEASONFIELD_AVERAGE_NDVI/n-planned/<VALUE>/thumbnail.png

Same goes for other requests.

**Comment by LNArtus** [comment]
HI @vermeulendivan  Talk to Vincent, you can add a fixed value n planned for the coverage panel and add a new parameter like for the yield average, which would be called N planned, that will be great for us.
