### ISSUE TITLE
No indexed map 

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#207]
**Describe the bug**
When the user test on the US platform, and want to get indexed map (same for all indexed map). there is no result.

![image](https://user-images.githubusercontent.com/69202500/161060316-5f5a28ba-1e9f-4d5c-b364-c19758af624c.png)
![image](https://user-images.githubusercontent.com/69202500/161060359-e22c1c97-3f0e-4fb2-b8c4-7593d3371196.png)

**Comment by LNArtus** [comment]
A new message come from the coverage parameter , @Samweli  can you regards this please ?

![image](https://user-images.githubusercontent.com/69202500/161060652-b3ef7ed1-99ce-4afb-81e9-6bca14cce42d.png)

**Comment by Samweli** [comment]
Hi @LNArtus, I'm taking a look and will get back to you shortly.

**Comment by Samweli** [comment]
@LNArtus can you share the data you have used, so I can reproduce the error on my side, thanks.

**Comment by LNArtus** [comment]
HI @Samweli, yes, here is the wkt of the polygon on the US area : MultiPolygon (((-94.64445673926874747 43.74670608953211826, -94.63447391619469329 43.74672755270827196, -94.63447391619469329 43.73610233957576554, -94.63601887690855108 43.73616674048638941, -94.63554350438121787 43.73640287656610326, -94.6354543720323278 43.73655314449563747, -94.63587032299373902 43.73700394602165886, -94.63747470527350458 43.73685367922341527, -94.6372073082268912 43.73599500457081035, -94.63607829847445885 43.73590913642832589, -94.63604858769150496 43.73599500457081035, -94.63450362697766138 43.73597353754672667, -94.63453333776061527 43.73238843656938712, -94.64457558240057722 43.73240990487865787, -94.64442702848579358 43.74666316315671821, -94.64445673926874747 43.74670608953211826)))
 I test on the production platform directly, made a request on all map type and got the above error message

**Comment by vermeulendivan** [comment]
@LNArtus Thanks for the data! Found the issue and fixed it. Will shortly get back to you via email.
