### ISSUE TITLE
default value of number of zones not equal to 0

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#209]
When we are on the settings panel and after choosing a map type, when we want to add the product to the layer, the number of zones is not equal to zero. 

**To Reproduce**
1. Go to the coverage panel center
2. Click on elevation map type (exemple)
3. Scroll down and click on Search map
4. The user is redirectly to the parameters panel, the number of zones parameters is equal  to the last selected number,

**Expected behavior**
The number of zones need to be equal to 0.

**Screenshots**

![number_zones](https://user-images.githubusercontent.com/69202500/164004199-7a39939d-6320-4925-b168-826deb417d2c.png)

**Additional context**
The user do not need to choose a number of zone except if they want to zone their map. So the default value of the parameter need to be equal to 0.

**Comment by vermeulendivan** [comment]
@LNArtus The default number of zones is 0, what happens if you changed the value at some point it is stored. This is how its been set up to work prior to making the recent improvements.

**Comment by LNArtus** [comment]
@vermeulendivan Would it be possible not to store the last value? On the specifications I specify that when the user is on the last parameter he should not see the value > 1 ?

**Comment by vermeulendivan** [comment]
@LNArtus Yes it can be done. But all of the parameters is stored - this not something we added, but has already been build into the plugin. Should all of the last parameters not be stored? Or should it only be the zones parameter?

**Comment by LNArtus** [comment]
@vermeulendivan All may not be stored, returning to zero each time the user returns to the first panel is better. I have not observed this problem with the other parameters but if you tell me that it's in the same spirit then you have to set them all to zero It's the user who chooses when he wants to change the value or not
