### ISSUE TITLE
Elevation map issue

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#210]
**Describe the bug**
Elevation map did not working.

**To Reproduce**
1. Go to panel center and choose the elevation map type
2. Click on Search map
3. Scroll down and see the error map creation 

**Expected behavior**
When we are on last the settings panel (parameter panel) and after to choose the png output format, we should see the the elevation product map adding to the layer.

**Screenshots**
what we should see : 
![good_elevation_map](https://user-images.githubusercontent.com/69202500/164011590-3f1a320c-747f-48d7-8c7e-fce2e6900367.png)
What the user is currently see : 
![wrong_elevation_map](https://user-images.githubusercontent.com/69202500/164011694-adcc66b6-17a3-46be-9f7a-0bda4ce68d00.png)

**Comment by vermeulendivan** [comment]
@LNArtus Not sure what is causing this, will look into it.

**Comment by LNArtus** [comment]
@vermeulendivan  thanks let me know if you want a exemple API call.
