### ISSUE TITLE
Default n planned value equal to 1

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#211]
**Describe the bug**
When we are on the first panel seeting (map parameter panel ), we whould be able to see an n-planned value equal to zero.

**To Reproduce**
1. Go to map parameter panel
2. Scroll down to see the n planned value equal to 1

**Expected behavior**
As a GEOSYS user I would like to have **the “nitrogen -planned value ” at 0** by default  in the map parameter panel

**Screenshots**

![n_planned_value_error](https://user-images.githubusercontent.com/69202500/164013351-27f79240-8b22-42e6-b898-9d5e163f6fd3.png)

**Comment by vermeulendivan** [comment]
@LNArtus At first did set the default to zero, but then got no result - so assumed the value cannot equal zero. From a value of 1 it works perfect.

**Comment by vermeulendivan** [comment]
@LNArtus Should the max be 100? And should it be decimal or just integer?

**Comment by LNArtus** [comment]
value cannot equal to zero when the user want to create nitorgen map but they know that they need to inter a n planned value to get the map so it strange to have a number, every time, equal to 1 and not 0. This parameter need to be change just for 4  maps and not for the other one. if it's at 1 it's quite confusing for the other types of map
