### ISSUE TITLE
Issue on Nitrogen LAI map 

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#212]
**Describe the bug**
 No notrogen map are created if we choose a polygon on europe side and when we choose a map type equal to  **inseasonfield_average_lai map type**

**To Reproduce**
1. Authentication on the production europe 
2. Go to coverage panel center and choose the **inseasonfield_average_lai** map type
3. Choose a n planned value equal to 80
4. Scroll down and click on Search map 
5. See error => no coverage for the map choose

**Expected behavior**
As a GEOSYS user I would like to be able to create an LAI Nitrogen map on a polygon located in europe.

**Screenshots**

![nitrogene_map_lai_issue](https://user-images.githubusercontent.com/69202500/164021261-fdccde3c-0d73-44e8-a730-633da1a54298.png)

Request made on the production europe and for a field in france  to verify the result on QGIS : 

{
  "Geometry": "MultiPolygon (((1.66884653867381183 43.59019247857889923, 1.67026680245843262 43.5900335001322361, 1.67058958968221005 43.59034210496863437, 1.67336555980669632 43.5900896102201898, 1.67430809850012619 43.5883595251166156, 1.6738820193647399 43.58817248591049776, 1.67384328489788659 43.58797609411855944, 1.67393366532054433 43.58789192601156515, 1.66882071569590962 43.58517977956837086, 1.66836881358262112 43.58585315146790151, 1.66847210549422997 43.5871811684148156, 1.66894983058542024 43.58712505561552319, 1.66940173269870917 43.58694736473934483, 1.66977616587829081 43.58674161675371295, 1.66987945778989966 43.586788377721291, 1.66942755567661116 43.58705023846843574, 1.67029262543633461 43.58763942098442357, 1.66862704336164325 43.58866813853602906, 1.66884653867381183 43.59019247857889923)))",
  "Crop": {
    "Id": "TRITICALE"
  },
  "SowingDate": "2022-02-01"
}
[
    {
        "coverageType": "CLEAR",
        "image": {
            "id": "IKc73hpUQ6uDL8o4BuOsu0b7aIxIgsw5khEBq747Ahg",
            "availableBands": [
                "Nir",
                "Red",
                "Blue",
                "Green",
                "RedEdge1",
                "RedEdge2",
                "RedEdge3"
            ],
            "sensor": "SENTINEL_2",
            "soilMaterial": "VEGETATION",
            "spatialResolution": 10.0,
            "weather": "DRY",
            "zenithAngleInDegree": 10.9172516,
            "date": "2022-04-17"
        },
        **"maps": [
            {
                "type": "INSEASONFIELD_AVERAGE_LAI"
            }**
        ],
        "seasonField": {
            "id": "ven3jqv",
            "customerExternalId": "IIxhALeMP/4VwvaW5yz76TMmOhsjPaNvmRiUS3DSQ4o="
        }
    },
    {

**Additional context**

When we test on Postman side and with the same paramter like on the QGIS plug-in we can see : 
![right_nitrogen_lai_map](https://user-images.githubusercontent.com/69202500/164022080-4036aec9-f0c4-4694-b3c1-7819e1698738.png)

**Comment by LNArtus** [comment]
same for the model map reverse lai.

**Comment by vermeulendivan** [comment]
@LNArtus I'm getting results for both INSEASONFIELD_AVERAGE_LAI and INSEASONFIELD_AVERAGE_REVERSE_LAI. It is done exactly the same manner as the NDVI versions, all that differs is the key (INSEASONFIELD_AVERAGE_LAI and INSEASONFIELD_AVERAGE_REVERSE_LAI). But I do remember having issues with these two cases (I think I pointed this out to you), but now it works.

The polygon you posted:

INSEASONFIELD_AVERAGE_LAI
![image](https://user-images.githubusercontent.com/79740955/164469917-f3a11228-4df9-44aa-9bff-0eeb6d78c40f.png)

INSEASONFIELD_AVERAGE_REVERSE_LAI
![image](https://user-images.githubusercontent.com/79740955/164470521-22f5a15c-ea90-4122-8781-7049985ebb2b.png)

Here is another area I tested in EU:

INSEASONFIELD_AVERAGE_LAI
![image](https://user-images.githubusercontent.com/79740955/164469053-8732b258-4e0a-4132-9b2e-286e5941fa0a.png)

INSEASONFIELD_AVERAGE_REVERSE_LAI
![image](https://user-images.githubusercontent.com/79740955/164469242-ee283165-8c3b-4c79-bd76-7e7fb5a044b6.png)

**Comment by LNArtus** [comment]
Ok great thank you for the feedback. You can close the ticket in consequently it's maybe just in our side, sometime it's work well sometime not.

**Comment by vermeulendivan** [comment]
This works as it should. See above exampels
