### ISSUE TITLE
No soil map on the last version of the plug-in

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#232]
**Describe the bug**
No soil map on the last version 
![image](https://user-images.githubusercontent.com/69202500/168566782-dec9ad2c-6dd8-41e4-ab5c-724871d12351.png)

**Comment by vermeulendivan** [comment]
@LNArtus Soil map only shows for one of the area options, US in this case. 
Here is a printscreen from the document stating it should only be for the US.
![image](https://user-images.githubusercontent.com/79740955/175519641-bbf2fc9a-4966-44a6-813e-e65cf9950f88.png)

**Comment by vermeulendivan** [comment]
Can I close this issue?

**Comment by LNArtus** [comment]
Yes
