### ISSUE TITLE
Soil map has no png format

### ISSUE THREAD

**Issue by vermeulendivan** [earthdaily/qgis-plugin#237]
This has been changed to png.kmz as requested, it will be changed back to png

**Comment by LNArtus** [comment]
SOIL map has no colors : 

![image](https://user-images.githubusercontent.com/69202500/175557500-311b56e3-447a-481a-bacc-90a0ab839236.png)

What is expected : 

![image](https://user-images.githubusercontent.com/69202500/175557585-64414525-81f2-4cef-ba35-8321cfcaed03.png)

**Comment by vermeulendivan** [comment]
@LNArtus Created a separate issue for the soil symbology

**Comment by vermeulendivan** [comment]
PNG works fine. Seems to be shp
![image](https://user-images.githubusercontent.com/79740955/178145149-7bd33216-b5b2-417d-8cf2-f2dd8f7ae8b5.png)
