### ISSUE TITLE
Map type coverage results shows more results than it should (includes other polygons)

### ISSUE THREAD

**Issue by vermeulendivan** [earthdaily/qgis-plugin#238]
Reflectance map coverage results shows more results than it should

**Comment by vermeulendivan** [comment]
@LNArtus Attempted to duplicate this, but works perfect on my side. Did you activate 'Selected features only' option? If this is not enabled, all polygons will be used. If this option is enabled, then it will only use the selected polygons.
![image](https://user-images.githubusercontent.com/79740955/178141556-2887b274-8187-4c48-aa13-96b26b8cdcbc.png)

**Comment by LNArtus** [comment]
This one can be close

**Comment by vermeulendivan** [comment]
This issue has been resolved
