### ISSUE TITLE
Regression QGIS plugin - new SAMZ feature - identical thumbnails 

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#249]
**Describe the bug**

When the user want to create SAMZ product, after to select their field boundery and select the SAMZ product type, on the coverage search results panel, the user see that all the thumbnails are same and he list of images that we can use for SAMZ maps have a zoning map thumbnail instead of an NDVI thumbnail.

**To Reproduce**
1. Go to the coverage parameters panel

![image](https://user-images.githubusercontent.com/69202500/197495771-32b7d4a3-74f4-4549-bf23-9362abc784af.png)

1. Select the field boundery
2. Select the SAMZ product map type 
3. Select start and end date
4. Scroll down and click on Create Map button
6. See error

![Image1](https://user-images.githubusercontent.com/69202500/197503724-e7d54766-6955-427c-895e-e91275de00e9.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/69202500/197550369-38bf4065-777c-4d46-97fe-4e97e6957e53.png)
- When the user want to create a SAMZ map, all the thumbnail should be a IN season NDVI map.
- When the user want to select just one date : the plug-in will trigger the SAMZ auto 
- When the user want to select more thant one date , example the 2022-04-30 and the 2022-04-03 : the plug-in will trigegr the SAMZ custom. 

SAMZ maps creation, should be differentes between all date, even if we select one or more than one image date.

**Additional context**

**Comment by vermeulendivan** [comment]
@LNArtus SAMZ now shows NDVI. Been merged so closing this issue
![image](https://user-images.githubusercontent.com/79740955/216055834-dc5aeb80-5eec-46a1-b7f8-9b179a89a193.png)
