### ISSUE TITLE
Add the choice weather type on the coverage parameter panel

### ISSUE THREAD

**Issue by LNArtus** [earthdaily/qgis-plugin#250]
**Describe the solution you'd like**
As a user I would like to be able to choose, bellow the button "choose a sensor type" , a weather type option. 
The user will have those differents choice : 
HOT|COLD|WET|DRY

**Additional context**

End point to use : /season-fields/{seasonFieldId}/catalog-imagery
filter type : image.weather

**Comment by LNArtus** [comment]
this is a improvement ticket.

**Comment by vermeulendivan** [comment]
The new weather options should be added here:
![image](https://user-images.githubusercontent.com/79740955/202996510-57920666-1102-4580-9539-8932fc1c29fa.png)

**Comment by vermeulendivan** [comment]
@LNArtus Weather types has been added:
![image](https://user-images.githubusercontent.com/79740955/216056130-901b19ee-5645-47d3-9d01-b5d84f14901b.png)
Weather type shown on the results
![image](https://user-images.githubusercontent.com/79740955/216056282-e3a83e3a-cc3c-4150-bb7b-8668ac020f17.png)
Closed this issue, as its been merged.
