### ISSUE TITLE
Description updated for the Geosys plugin help center

### ISSUE THREAD

**Issue by vermeulendivan** [earthdaily/qgis-plugin#251]
These are updated/revisions of the descriptions of tools, features, map types provided by the plugin:
- Add description of sample map
- Correction of map descriptions
- User credentials description improvement

![image](https://user-images.githubusercontent.com/79740955/202999789-3f9ffafe-865d-4f1f-8418-84c64ce13457.png)

**Comment by mal147** [comment]
NDWI - Provides the in-season Normalized Difference Water Index.

SLOPE - Provides the slope map.

**Comment by mal147** [comment]
NDMI - Provides the in-season Normalized Difference Moisture Index.

**Comment by mal147** [comment]
+ add a description for SAMPLEMAP as it's empty today
•	SAMPLEMAP – Provides a zoning map based on sample points provided by the user
