### ISSUE TITLE
RX map creation

### ISSUE THREAD

**Issue by vermeulendivan** [earthdaily/qgis-plugin#252]
The user should be allowed to create Rx maps. Quick summary:
- Added fetch for RX maps (coverage)
- Creation of RX maps

Fetch RX map parameters for user:
- Given that the user is on the last parameters panel (map creation), when choosing to fetch RX map then they shall be able to click on a button and choose a number of zones; and
- Given that the user has choosing the number of zones and after to have click on the “create map” button, a new panel will open.
![image](https://user-images.githubusercontent.com/79740955/203002899-bc29d146-feb8-40cf-b493-14dd08497767.png)

New section for RX maps:
- Given that the user has choosing the number of zones and after to have click on the “create map” button, a new panel will open;
- The new panel should include the following options:
- RX map name
- Each zone of the RX map
- Average area value for each zone (hectare or other, depending on the user creation)
![image](https://user-images.githubusercontent.com/79740955/203004625-0f0f9a19-620d-47b4-81af-a22709362910.png)
The new panel should have the following parameters:
- Values for each zone, which can be changed
- The default value should correspond to each dataset (server side or client side calculation?)
- Input name should be the column name chosen by the user in the first panel (does this refer to the coverage panel?)
- The user should be able to choose one of the following formats: shp, png, tiff or kmz (this should already be build into the plugin)

Two options on where to choose format:
- Come back to previous panel?
- Add to new panel?

API workflow:
1. Creation of the Rx map:
- Map ID from sample map
- Number of zones
2. Save the RX map ID
3. Save the area size for each zone (client side or server side calc?)
4. Create the RX map by the user:
- The user can change the value if they want to - the API response will show the number of updated values (count?)
- Create the RX map based on the chosen format

**Comment by vermeulendivan** [comment]
API End points to use:
- Swagger: https://api-pp.geosys-na.net/field-level-maps/v4/swagger/index.html?urls.primaryName=Field%20level%20maps%20(with%20shortcuts)
- Production platform: https://api.geosys-na.net/
- Testing platform: http://api-pp.geosys-na.net/
Steps:
- POST: /field-level-maps/v4/maps/sample/samplemap
- GET: /field-level-maps/v4/maps/{{Sourcemap_id}}/thumbnail.png
- POST: /field-level-maps/v4/maps/rx-map/
- GET: /field-level-maps/v4/maps/{{rxmap_id}}

**Comment by osundwajeff** [comment]
- [ ] Creation for RX maps (from coverage search)

**Comment by osundwajeff** [comment]
- [ ] New section for RX parameters

**Comment by osundwajeff** [comment]
- [ ] Map creation on chosen format

**Comment by osundwajeff** [comment]
Hi @mal147 
Do you have an example of a payload used for rx-maps?

**Comment by mal147** [comment]
Hello @osundwajeff ,
[RxMap_MPv5.postman_collection.json](https://github.com/user-attachments/files/17866561/RxMap_MPv5.postman_collection.json)
I have created this specific Postman collection to showcase you how to create a Rxmap.

After a selection of a base reference map (NDVI for example) and a number of zones by the user (the map id and the number of zones must be stored to be used on next request).

**Create a Rx Map from zoned base reference map:**
`import requests
import json

url = "http://api.geosys-na.net/field-level-maps/v5/maps/rx-map?colorMapId=RX&storeRequest=true&directLinks=true&zoning=true&minZoneSize=0.01"

payload = json.dumps({
  "name": "MyRx MPv5",
  "tags": [
    "RX_MAP"
  ],
  "sourceMapId": "4FBOtVzFALrcVH2pZXFv6N",
  "zoneCount": "5"
})
headers = {
  'Content-Type': 'application/json',
  'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRDQjZGQ0NEM0MyMjI5QzdFRTk1QTZBOUJDQkRCRTI2RjMwNjg1ODRSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6IjNMYjh6VHdpS2NmdWxhYXB2TDItSnZNR2hZUSJ9.eyJuYmYiOjE3MzIyMTk5MTcsImV4cCI6MTczMjIyMzUxNywiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtbmEuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1uYS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJtYXBwcm9kdWN0X2FwaSIsInN1YiI6IjEwMDExMTIzNSIsImF1dGhfdGltZSI6MTczMjIxOTkxNywiaWRwIjoibG9jYWwiLCJnZW82X3N1YiI6IlFnSTZPcmJSakVzUmZpTlp0VlBwNCIsImlhdCI6MTczMjIxOTkxNywic2NvcGUiOlsib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInBhc3N3b3JkIl19.aaW4Zd2MPFAmwjvA6fGDLcqCl43mGNt5201ttjLxYrykHDJ6ftKXxj9-L0O_knjegayaxQGTubQBFSOjWNaBRvkWKIZJ4BHEY0TtYpVCD-EGGyuasEajMv_7UWgWiv0PY8c9FA1Gv6b15O3V0mRKosDSaUnBCLNqShMYqZpokckNJqDRiXrmHgac4Br0wQ5DUQ6HpxZ1iAjF1UhvTtM2sCGU1VymbV6DSK2QSNNF8b42SeLBeQyNNA54pcRf73gHzIT5EQ_edoot-yXfOCVrTwvnleicW9KPYjSmZC2h-ixJ4NAQXIgaOsc93sBvOOQXxKyPgsAhHkqzGfNVR0kWGw'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)
`

**Attribute values to the Rx Map using the value defined by the user on the new window (2nd screenshot at the top of the ticket)**

`import requests
import json

url = "http://api.geosys-na.net/field-level-maps/v5/maps/CXPvlY6KMuDNUhXe2lYYT/rx-map"

payload = json.dumps([
  {
    "op": "add",
    "path": "/parameters/zones/0/attributes/value",
    "value": "50"
  },
  {
    "op": "add",
    "path": "/parameters/zones/1/attributes/value",
    "value": "60"
  },
  {
    "op": "add",
    "path": "/parameters/zones/2/attributes/value",
    "value": "70"
  },
  {
    "op": "add",
    "path": "/parameters/zones/3/attributes/value",
    "value": "80"
  },
  {
    "op": "add",
    "path": "/parameters/zones/4/attributes/value",
    "value": "100"
  }
])
headers = {
  'Content-Type': 'application/json',
  'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRDQjZGQ0NEM0MyMjI5QzdFRTk1QTZBOUJDQkRCRTI2RjMwNjg1ODRSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6IjNMYjh6VHdpS2NmdWxhYXB2TDItSnZNR2hZUSJ9.eyJuYmYiOjE3MzIyMTk5MTcsImV4cCI6MTczMjIyMzUxNywiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtbmEuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1uYS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJtYXBwcm9kdWN0X2FwaSIsInN1YiI6IjEwMDExMTIzNSIsImF1dGhfdGltZSI6MTczMjIxOTkxNywiaWRwIjoibG9jYWwiLCJnZW82X3N1YiI6IlFnSTZPcmJSakVzUmZpTlp0VlBwNCIsImlhdCI6MTczMjIxOTkxNywic2NvcGUiOlsib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInBhc3N3b3JkIl19.aaW4Zd2MPFAmwjvA6fGDLcqCl43mGNt5201ttjLxYrykHDJ6ftKXxj9-L0O_knjegayaxQGTubQBFSOjWNaBRvkWKIZJ4BHEY0TtYpVCD-EGGyuasEajMv_7UWgWiv0PY8c9FA1Gv6b15O3V0mRKosDSaUnBCLNqShMYqZpokckNJqDRiXrmHgac4Br0wQ5DUQ6HpxZ1iAjF1UhvTtM2sCGU1VymbV6DSK2QSNNF8b42SeLBeQyNNA54pcRf73gHzIT5EQ_edoot-yXfOCVrTwvnleicW9KPYjSmZC2h-ixJ4NAQXIgaOsc93sBvOOQXxKyPgsAhHkqzGfNVR0kWGw'
}

response = requests.request("PATCH", url, headers=headers, data=payload)

print(response.text)
`

**Then, deliver the RX map to the user**

`import requests

url = "http://api.geosys-na.net/field-level-maps/v5/maps/CXPvlY6KMuDNUhXe2lYYT?directlinks=true"

payload = {}
headers = {
  'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRDQjZGQ0NEM0MyMjI5QzdFRTk1QTZBOUJDQkRCRTI2RjMwNjg1ODRSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6IjNMYjh6VHdpS2NmdWxhYXB2TDItSnZNR2hZUSJ9.eyJuYmYiOjE3MzIyMTk5MTcsImV4cCI6MTczMjIyMzUxNywiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtbmEuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1uYS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJtYXBwcm9kdWN0X2FwaSIsInN1YiI6IjEwMDExMTIzNSIsImF1dGhfdGltZSI6MTczMjIxOTkxNywiaWRwIjoibG9jYWwiLCJnZW82X3N1YiI6IlFnSTZPcmJSakVzUmZpTlp0VlBwNCIsImlhdCI6MTczMjIxOTkxNywic2NvcGUiOlsib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInBhc3N3b3JkIl19.aaW4Zd2MPFAmwjvA6fGDLcqCl43mGNt5201ttjLxYrykHDJ6ftKXxj9-L0O_knjegayaxQGTubQBFSOjWNaBRvkWKIZJ4BHEY0TtYpVCD-EGGyuasEajMv_7UWgWiv0PY8c9FA1Gv6b15O3V0mRKosDSaUnBCLNqShMYqZpokckNJqDRiXrmHgac4Br0wQ5DUQ6HpxZ1iAjF1UhvTtM2sCGU1VymbV6DSK2QSNNF8b42SeLBeQyNNA54pcRf73gHzIT5EQ_edoot-yXfOCVrTwvnleicW9KPYjSmZC2h-ixJ4NAQXIgaOsc93sBvOOQXxKyPgsAhHkqzGfNVR0kWGw'
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)
`

Please don't hesitate for any questions you have!

cc @mvmaltitz

**Comment by osundwajeff** [comment]
Thanks @mal147, I'll go through it

**Comment by mvmaltitz** [comment]
Testing Result:
![Image](https://github.com/user-attachments/assets/85eb3369-67cb-4c95-a653-56e7418fae34)

![Image](https://github.com/user-attachments/assets/85f42161-475a-4ae8-a9ba-493ce051ec21)
