### ISSUE TITLE
Testing service option

### ISSUE THREAD

**Issue by vermeulendivan** [earthdaily/qgis-plugin#253]
- Given that the user is on the option settings panel, they will have the possibility to click on a button to define whether they want to test our geosys APIs or not
![image](https://user-images.githubusercontent.com/79740955/203011527-4e291def-6725-49d1-8fdf-316270e9f092.png)

- Given that the user is on the option settings panel and on the testing section part, if they want to use the plugin on our production platform, the button should be disabled by default.
- Remove the Geographical region section, and only leave the testing option
![image](https://user-images.githubusercontent.com/79740955/203011811-eadedae6-f72c-4d91-b904-d9e9a7b3ede9.png)

**Comment by vermeulendivan** [comment]
Move settings to the QGIS options panel?

**Comment by mvmaltitz** [comment]
Testing Results:
![Image](https://github.com/user-attachments/assets/48f24847-9086-4c5c-b325-c91a6b2b88b9)
