### ISSUE TITLE
Update list of products & change product name

### ISSUE THREAD

**Issue by mvmaltitz** [earthdaily/qgis-plugin#271]
## `Expectations: 
1. As a EarthDaily user I would like to be able to get NDWI product
2. As a EarthDaily user I would like to be able to get SLOPE product
3. As a EarthDaily user I don’t want to have INSEASONPARTIAL_NDVI in the list of products
4. As a EarthDaily user I don’t want to have INSEASONPARTIAL_EVI in the list of products
5. As a EarthDaily user I want to have the name of products without “INSEASON_”
![Image](https://github.com/user-attachments/assets/a50375c8-2b0d-477d-8e77-247552cb4cc2)

## Acceptance criteria:
1. Given that the user is on the Coverage Parameters panel, when choosing a map product type then they will be able to select the map product type NDWI.
2. Given that the user is on the Coverage Parameters panel, when choosing a map product type then they will be able to select the map product type NDMI.
3. Given that the user is on the Coverage Parameters panel, when choosing a map product type then they will be able to select the map product type SLOPE.
4. Given that the user is on the Coverage Parameters panel, when choosing a map product type then they will not be able to select the map product type INSEASONPARTIAL_NDVI.
5. Given that the user is on the Coverage Parameters panel, when choosing a map product type then they will not be able to select the map product type INSEASONPARTIAL_EVI.
6. Given that the user is on the Coverage Parameters panel, when choosing a map product type then they will be able to select the map product type NDVI instead of INSEASON_NDVI. This update is applied to all other product which start with “INSEASON_”.

## API Examples:
Here is an example of the request:
**1- NDWI**
curl --location 'http://api-pp.geosys-na.net/field-level-maps/v5/maps/base-reference-map/NDWI' \
--header 'X-EDK-ProductFormat: webp' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer null' \
--data '{
  "image": {
    "id": "sentinel-2-l2a|S2A_31TCJ_20240419_1_L2A"
  },
  "seasonField":         
  {
    "geometry": "POLYGON ((1.167641 43.68935, 1.168499 43.686339, 1.171288 43.686526, 1.170516 43.683888, 1.167555 43.684508, 1.162877 43.681219, 1.160388 43.682491, 1.161547 43.684136, 1.164079 43.685036, 1.163778 43.68606, 1.162963 43.686526, 1.160216 43.685067, 1.159058 43.684322, 1.156182 43.684074, 1.154981 43.684229, 1.152792 43.686526, 1.152534 43.68696, 1.154895 43.688294, 1.156569 43.687053, 1.158714 43.68727, 1.160517 43.688481, 1.163821 43.690094, 1.164808 43.688574, 1.167641 43.68935))"
    
  }
}'

**2- NDMI**
curl --location 'http://api-pp.geosys-na.net/field-level-maps/v5/maps/base-reference-map/NDMI' \
--header 'X-EDK-ProductFormat: webp' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer null' \
--data '{
  "image": {
    "id": "sentinel-2-l2a|S2A_31TCJ_20240419_1_L2A"
  },
  "seasonField":         
  {
    "geometry": "POLYGON ((1.167641 43.68935, 1.168499 43.686339, 1.171288 43.686526, 1.170516 43.683888, 1.167555 43.684508, 1.162877 43.681219, 1.160388 43.682491, 1.161547 43.684136, 1.164079 43.685036, 1.163778 43.68606, 1.162963 43.686526, 1.160216 43.685067, 1.159058 43.684322, 1.156182 43.684074, 1.154981 43.684229, 1.152792 43.686526, 1.152534 43.68696, 1.154895 43.688294, 1.156569 43.687053, 1.158714 43.68727, 1.160517 43.688481, 1.163821 43.690094, 1.164808 43.688574, 1.167641 43.68935))"
    
  }
}'

**3- SLOPE**
curl --location 'http://api-pp.geosys-na.net/field-level-maps/v5/maps/topology-map/SLOPE' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--data '{
  "seasonField":         
  {
    "geometry": "POLYGON ((1.167641 43.68935, 1.168499 43.686339, 1.171288 43.686526, 1.170516 43.683888, 1.167555 43.684508, 1.162877 43.681219, 1.160388 43.682491, 1.161547 43.684136, 1.164079 43.685036, 1.163778 43.68606, 1.162963 43.686526, 1.160216 43.685067, 1.159058 43.684322, 1.156182 43.684074, 1.154981 43.684229, 1.152792 43.686526, 1.152534 43.68696, 1.154895 43.688294, 1.156569 43.687053, 1.158714 43.68727, 1.160517 43.688481, 1.163821 43.690094, 1.164808 43.688574, 1.167641 43.68935))"
  }
}'

**5- NDVI instead of INSEASON_NDVI**

curl --location 'http://api-pp.geosys-na.net/field-level-maps/v5/map-sets/base-reference-map/NDVI?directLinks=true' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer null' \
--data '{
    "mapParams":
    [
        { 
            "image": 
            {
                "id": "sentinel-2-l2a|S2A_31TCJ_20240509_0_L2A"
            },
            "seasonField":         
            {
                "geometry": "POLYGON ((1.167641 43.68935, 1.168499 43.686339, 1.171288 43.686526, 1.170516 43.683888, 1.167555 43.684508, 1.162877 43.681219, 1.160388 43.682491, 1.161547 43.684136, 1.164079 43.685036, 1.163778 43.68606, 1.162963 43.686526, 1.160216 43.685067, 1.159058 43.684322, 1.156182 43.684074, 1.154981 43.684229, 1.152792 43.686526, 1.152534 43.68696, 1.154895 43.688294, 1.156569 43.687053, 1.158714 43.68727, 1.160517 43.688481, 1.163821 43.690094, 1.164808 43.688574, 1.167641 43.68935))"
                
            }
        }
    ]
}'

## API Endpoints to use:
Swagger:   https://api-pp.geosys-na.net/field-level-maps/v5/swagger
Catalog imagery: /field-level-maps/v5/ season-fields/catalog-imagery

**Comment by osundwajeff** [comment]
Hi @mal147 

I would like to confirm one detail regarding this ticket: it requires that all map products exclude the `INSEASON_` prefix. However, I noticed that the `LAI` endpoint still uses `INSEASON_`. Should this be considered an exception?

![image](https://github.com/user-attachments/assets/f46c05bf-7cc0-4ebe-957f-c471be6a879d)

cc: @Samweli @mvmaltitz

**Comment by mal147** [comment]
Hi @osundwajeff,
No, you can use LAI only, it should works as well as INSEASON_LAI. 
I just forgot to do the change on the Postman collection.
Thanks

**Comment by osundwajeff** [comment]
Thanks for the feedback @mal147

**Comment by mvmaltitz** [comment]
Test Results:
![Image](https://github.com/user-attachments/assets/968590b6-6eda-4805-9ef9-cb3683d3ede8)

NDWI:
@osundwajeff please check
![Image](https://github.com/user-attachments/assets/b6f94c8f-b48e-4ac2-8acc-9d17f1074994)
