### ISSUE TITLE
Change request to get Hotspot

### ISSUE THREAD

**Issue by mvmaltitz** [earthdaily/qgis-plugin#274]
## Expectations: 
1. As a EarthDaily user I would like to be able to continue to get hotspot on vegetation, SaMZ and elevation maps

## API Examples:
Request url for vegetation maps
[https://hotspots-dev.aws-dev.geosys.com/hotspots-processor/vegetation?MapType=NDVI&Type=Polygon&Position=Average&ZonesCount=5&%24epsg-out=4326](https://hotspots-dev.aws-dev.geosys.com/hotspots-processor/vegetation?MapType=NDVI&Type=Polygon&Position=Average&ZonesCount=5&$epsg-out=4326)

**Body/Curl**
curl -X 'POST' \
  'https://hotspots-dev.aws-dev.geosys.com/hotspots-processor/vegetation?MapType=NDVI&Type=Polygon&Position=Average&ZonesCount=5&%24epsg-out=4326' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "geometry": "POLYGON ((-56.785919346530768 -21.208154463301554 , -56.79078750820733 -21.206043784434833 , -56.790973809206818 -21.206069651656232 , -56.791373799079636 -21.197107091323097 , -56.785129186971687 -21.196010916846863 , -56.781397554331065 -21.19535575112814 , -56.777108478217059 -21.202038412606473 , -56.778435977920665 -21.211398619037478 , -56.785919346530768 -21.208154463301554))",
  "image_id": [
    "sentinel-2-l2a|S2A_21KWS_20231030_0_L2A"
  ]
}'

Example of output : {
  "Metadata": {
    "geometry": "POLYGON ((-56.785919346530768 -21.208154463301554 , -56.79078750820733 -21.206043784434833 , -56.790973809206818 -21.206069651656232 , -56.791373799079636 -21.197107091323097 , -56.785129186971687 -21.196010916846863 , -56.781397554331065 -21.19535575112814 , -56.777108478217059 -21.202038412606473 , -56.778435977920665 -21.211398619037478 , -56.785919346530768 -21.208154463301554))",
    "image_id": [
      "sentinel-2-l2a|S2A_21KWS_20231030_0_L2A"
    ]
  },
 "OutputData": {
    "Hotspots": [
      {
        "value": 0.1819155514240265,
        "segmentId": 3,
        "position": "Maximum",
        "geometry": "POINT (-56.787661624663045 -21.205570091733563)"
      },
      {
        "value": 0.18728332221508026,
        "segmentId": 3,
        "position": "Maximum",
        "geometry": "POINT (-56.787661624663045 -21.206030710039652)"
      },
      {
        "value": 0.2597501575946808,
        "segmentId": 3,
        "position": "Maximum",
        "geometry": "POINT (-56.77836406147241 -21.20088007810699)"
      },
     ...
      {
        "value": 0.22514928877353668,
        "segmentId": 4,
        "position": "Minimum",
        "geometry": "POINT (-56.77953187134177 -21.207370682397)"
      },
      {
        "value": 0.22268012166023254,
        "segmentId": 4,
        "position": "Minimum",
        "geometry": "POINT (-56.7797564501628 -21.208626895438567)"
},
      {
        "value": 0.28533098101615906,
        "segmentId": 5,
        "position": "Minimum",
        "geometry": "POINT (-56.77863355605765 -21.203853229026265)"
      },
      ...
      {
        "value": 0.17566251754760742,
        "segmentId": 3,
        "position": "Average",
        "geometry": "POINT (-56.78770654042725 -21.2054025938115)"
      },
      {
        "value": 0.1761159747838974,
        "segmentId": 3,
        "position": "Average",
        "geometry": "POINT (-56.7880209507767 -21.206240081522)"
      },
    ]
  }
}

## Request url for vegetation maps ans samples output
[https://hotspots-dev.aws-dev.geosys.com/hotspots-processor/vegetation/samples?MapType=NDVI&Type=Polygon&Position=Average&ZonesCount=5&%24epsg-out=4326&extension=shp.zip](https://hotspots-dev.aws-dev.geosys.com/hotspots-processor/vegetation/samples?MapType=NDVI&Type=Polygon&Position=Average&ZonesCount=5&$epsg-out=4326&extension=shp.zip)

**Body/Curl**
curl -X 'POST' \
  'https://hotspots-dev.aws-dev.geosys.com/hotspots-processor/vegetation/samples?MapType=NDVI&Type=Polygon&Position=Average&ZonesCount=5&%24epsg-out=4326&extension=shp.zip' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "geometry": "POLYGON ((-56.785919346530768 -21.208154463301554 , -56.79078750820733 -21.206043784434833 , -56.790973809206818 -21.206069651656232 , -56.791373799079636 -21.197107091323097 , -56.785129186971687 -21.196010916846863 , -56.781397554331065 -21.19535575112814 , -56.777108478217059 -21.202038412606473 , -56.778435977920665 -21.211398619037478 , -56.785919346530768 -21.208154463301554))",
  "image_id": [
    "sentinel-2-l2a|S2A_21KWS_20231030_0_L2A"
  ]
}'

Example of output : {
  "Metadata": {
    "geometry": "POLYGON ((-56.785919346530768 -21.208154463301554 , -56.79078750820733 -21.206043784434833 , -56.790973809206818 -21.206069651656232 , -56.791373799079636 -21.197107091323097 , -56.785129186971687 -21.196010916846863 , -56.781397554331065 -21.19535575112814 , -56.777108478217059 -21.202038412606473 , -56.778435977920665 -21.211398619037478 , -56.785919346530768 -21.208154463301554))",
    "image_id": [
      "sentinel-2-l2a|S2A_21KWS_20231030_0_L2A"
    ]
  },
  "OutputData": {
    "Hotspots": [
      {
        "value": 0.1819155514240265,
        "segmentId": 3,
        "position": "Maximum",
        "geometry": "POINT (-56.787661624663045 -21.205570091733563)"
      },
      {
        "value": 0.18728332221508026,
        "segmentId": 3,
        "position": "Maximum",
        "geometry": "POINT (-56.787661624663045 -21.206030710039652)"
      },
      {
        "value": 0.2597501575946808,
        "segmentId": 3,
        "position": "Maximum",
        "geometry": "POINT (-56.77836406147241 -21.20088007810699)"
      },
     ...
      {
        "value": 0.22514928877353668,
        "segmentId": 4,
        "position": "Minimum",
        "geometry": "POINT (-56.77953187134177 -21.207370682397)"
      },
      {
        "value": 0.22268012166023254,
        "segmentId": 4,
        "position": "Minimum",
        "geometry": "POINT (-56.7797564501628 -21.208626895438567)"
 },
      {
        "value": 0.28533098101615906,
        "segmentId": 5,
        "position": "Minimum",
        "geometry": "POINT (-56.77863355605765 -21.203853229026265)"
      },
      ...
      {
        "value": 0.17566251754760742,
        "segmentId": 3,
        "position": "Average",
        "geometry": "POINT (-56.78770654042725 -21.2054025938115)"
      },
      {
        "value": 0.1761159747838974,
        "segmentId": 3,
        "position": "Average",
        "geometry": "POINT (-56.7880209507767 -21.206240081522)"
      },
    ]
  }
}

## API Endpoints to use:
Swagger: https://hotspots-dev.aws-dev.geosys.com/docs#/Compute%20Hotspots%20on%20Vegetation%20maps/hotspots_processor_hotspots_processor_vegetation_post

## All details available here: 
[P3-Hotspots processor-310724-190525.pdf](https://earthdailyagro-my.sharepoint.com/:b:/g/personal/mathieu_almeida_earthdaily_com/EXmilHhMEsVHmWsXPPeina0BmaZrzqSkHdOP_yuuzVU9Xw?e=XWefZU)

**Comment by Samweli** [comment]
@mvmaltitz @mal147 https://hotspots-dev.aws-dev.geosys.com is not available and I couldn't access the attached [pdf](https://earthdailyagro-my.sharepoint.com/:b:/g/personal/mathieu_almeida_earthdaily_com/EXmilHhMEsVHmWsXPPeina0BmaZrzqSkHdOP_yuuzVU9Xw?e=XWefZU).

**Comment by mal147** [comment]
@Samweli sorry the url has changed since I have create the ticket.
The prod url is https://hotspots.aws.geosys.com/docs
[P3-Hotspotsprocessor-191124-1540.pdf](https://github.com/user-attachments/files/17817632/P3-Hotspotsprocessor-191124-1540.pdf)


I put here the updated pdf attached.
