### ISSUE TITLE
Parameter "limit" is broken: even when the number of max items per request is 100, the plugin shows only 20 images.

### ISSUE THREAD

**Issue by mvmaltitz** [earthdaily/qgis-plugin#276]
## Expectations: 
1. As a EarthDaily user I would like to be able to change the number of item available in the plugin. continue to get hotspot on zoning maps 
![Image](https://github.com/user-attachments/assets/92812b89-08de-4abc-aacd-4c91a12ebca0)

## API Examples:
CURL --LOCATION 'HTTP://API-PP.GEOSYS-NA.NET/FIELD-LEVEL-MAPS/V5/SEASON-FIELDS/CATALOG-IMAGERY?COVERAGEPERCENT=%24GTE%3A10&%24LIMIT=100&IMAGE.DATE=%24GTE%3A2023-01-01&MASK=AUTO' \
--HEADER 'CONTENT-TYPE: APPLICATION/JSON' \
--HEADER 'AUTHORIZATION: BEARER EYJHBGCIOIJSUZI1NIISIMTPZCI6IJE1NJDGRUYYMUYZRTZCNJJCRDI0MTLGMTQ0MEQ1OUU4QZM1QUIXMZHSUZI1NIISINR5CCI6IKPXVCISING1DCI6IKZXZI04ADGTYTJLOUPCBNHSQTFANK1OYXNUZYJ9.EYJUYMYIOJE3MJAXMDQYNTISIMV4CCI6MTCYMDEWNZG1MIWIAXNZIJOIAHR0CHM6LY9PZGVUDGL0ES5WCMVWCM9KLMDLB3N5CY1UYS5JB20VDJIUMSISIMF1ZCI6IMH0DHBZOI8VAWRLBNRPDHKUCHJLCHJVZC5NZW9ZEXMTBMEUY29TL3YYLJEVCMVZB3VYY2VZIIWIY2XPZW50X2LKIJOIBWFWCHJVZHVJDF9HCGKILCJZDWIIOIIXMDAXMTEYMZUILCJHDXROX3RPBWUIOJE3MJAXMDQYNTISIMLKCCI6IMXVY2FSIIWIZ2VVNL9ZDWIIOIJRZ0K2T3JIUMPFC1JMAU5ADFZQCDQILCJPYXQIOJE3MJAXMDQYNTISINNJB3BLIJPBIM9WZW5PZCISIM9MZMXPBMVFYWNJZXNZIL0SIMFTCII6WYJWYXNZD29YZCJDFQ.R1OVYY4-ZV-S3JUVCYWVLB6FL5IIFT3NS-GOBT73XKH_FBBZ6NJQDWKBNLB6IPNPA3FHZMEIRZFRTUJRSGH-_SYB70QL1E4D67SVWBDQG_BWYRLORMPZSW5A35SC_R653MR9L-WZDTRMBOGYIUALWLCYDC49GTZFJ-RPY-VNORFYRI4FVQ0SXSUBNNLR1VOYQUJ9ONEUTXZSF4YRL9SLLBDJB_NKVGXHBHTYUFCWFGDPUUDMNE4W3JZZREK1K9PQM4OQUJ98TBNEG_THECEICFMO3QI-W2POPROM_LRWKVYQON6I_JGA5SRCVYEJR8E07DFEASORAQ6IFYWV6JE5SA' \
--DATA '{
    "SEASONFIELDS":
    [
        {
            "GEOMETRY": "POLYGON ((1.167641 43.68935, 1.168499 43.686339, 1.171288 43.686526, 1.170516 43.683888, 1.167555 43.684508, 1.162877 43.681219, 1.160388 43.682491, 1.161547 43.684136, 1.164079 43.685036, 1.163778 43.68606, 1.162963 43.686526, 1.160216 43.685067, 1.159058 43.684322, 1.156182 43.684074, 1.154981 43.684229, 1.152792 43.686526, 1.152534 43.68696, 1.154895 43.688294, 1.156569 43.687053, 1.158714 43.68727, 1.160517 43.688481, 1.163821 43.690094, 1.164808 43.688574, 1.167641 43.68935))"
        }
    ]
}'

## API Endpoints to use:
Swagger:   https://api-pp.geosys-na.net/field-level-maps/v5/swagger
Catalog imagery: /field-level-maps/v5/season-fields/catalog-imagery

**Comment by mvmaltitz** [comment]
See ticket #248

**Comment by mvmaltitz** [comment]
@mal147 CC @osundwajeff 

Please could you advise us when the block has been resolved on your side.

**Comment by mal147** [comment]
Hi @mvmaltitz & @osundwajeff ,
After internal discussion, we would like to remove the "limit" parameter. This parameter is no more functional on the field level maps version 5 API.
The performance of our API is good enough to deliver an answer even the user will select a large period of time on the request.

I will create new ticket to remove the "limit" parameter on the front of the plugin.
Is it possible to you to remove this parameter on the back end ? 

Thank you!
cc @simon-geosys
