### ISSUE TITLE
Branding update for the EarthDaily plugin help center

### ISSUE THREAD

**Issue by mal147** [earthdaily/qgis-plugin#323]
Clicking on the help button on the plugin, users have access to this page: 
![image](https://github.com/user-attachments/assets/c23652bb-88ce-4c56-b45d-c3b67635d2a8)

1. We want to change the color of the banner, using:

HEX 00B2F4
RGB 0, 178, 244
CMYK 100, 27, 0, 4

![image](https://github.com/user-attachments/assets/017bfd86-4e8b-49ff-ac74-c95cde55bc9f)

2. Replace GEOSYS by EarthDaily on the banner.

3. Change the logo using this one

![EarthDaily](https://github.com/user-attachments/assets/d42b4e25-f8e8-4536-969d-77a32d67eab7)

4. At the end of the document, replace "The Geosys API developer portal is available here https://developer.geosys.com" by 
"To access more capabilities, EarthDaily python package and documentation are available on github:
- https://github.com/earthdaily/earthdaily-python-client 
- https://github.com/earthdaily/EDA-Documentation/tree/gh-pages"
![image](https://github.com/user-attachments/assets/ae834aad-9db6-45e5-9dac-df4f97976989)

**Comment by osundwajeff** [comment]
Hi @mal147 
I have been unable to access the logo, probably due to permissions.
Is it possible to send it via email?

cc: @mvmaltitz @Samweli

**Comment by mal147** [comment]
Hi @osundwajeff,
Email sent!
cc @mvmaltitz

**Comment by mvmaltitz** [comment]
@osundwajeff  Text is not visible on banner
![Image](https://github.com/user-attachments/assets/06316476-2cf3-498d-afd4-047476c22670)
