### ISSUE TITLE
Impossible to get coverage

### ISSUE THREAD

**Issue by vincentlel** [earthdaily/qgis-plugin#33]
**Describe the bug**
With the latest release, I selected a layer and the search parameter. Then when I hit the "Search map" button, new panel load but received an error.

Here is the WKT selected:
MultiPolygon (((-97.73379563999999675 41.51117234000000167, -97.73353815000000111 41.52155149000000023, -97.72950410999999349 41.52155149000000023, -97.72916078999999456 41.52116591000000057, -97.7274012599999935 41.52113377999999955, -97.727358339999995 41.52153541999999931, -97.72699355999999682 41.52174426999999923, -97.72598505000000557 41.52185673000000321, -97.72564173000000665 41.52196919000000008, -97.7256631900000059 41.52216196999999909, -97.7252125699999965 41.52214590999999899, -97.72512673999999322 41.52195311999999916, -97.72413969000000122 41.52190492999999805, -97.72416115000000048 41.51139729999999872, -97.73379563999999675 41.51117234000000167)))

here is the stack trace:
An error has occurred while executing Python code: 

TypeError: disconnect() failed between 'data_downloaded' and all its connections 
Traceback (most recent call last):
  File "C:/Users/VL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geosys-qgis-plugin-develop\geosys\ui\widgets\geosys_dockwidget.py", line 175, in show_next_page
    self.start_coverage_search()
  File "C:/Users/VL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geosys-qgis-plugin-develop\geosys\ui\widgets\geosys_dockwidget.py", line 405, in start_coverage_search
    self.search_threads.data_downloaded.disconnect()
TypeError: disconnect() failed between 'data_downloaded' and all its connections

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.6.0-Noosa Noosa, 58734527ab 

Python Path:
C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python
C:/Users/VL/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/VL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.6\bin\python37.zip
C:\PROGRA~1\QGIS3~1.6\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib
C:\Program Files\QGIS 3.6\bin
C:\PROGRA~1\QGIS3~1.6\apps\Python37
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\Pythonwin
C:/Users/VL/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/VL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geosys-qgis-plugin-develop
C:\Users\VL\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:/Users/VL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geosys-qgis-plugin-develop
C:\Users\VL\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:/GEOSYS/Application/Bridge/Testing

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version QGIS 3.6

**Additional context**
Using PUS account

**Comment by myarjunar** [comment]
have you test the authentication from the options dialog?
sorry, I can't replicate it. I got this result instead (same as postman)
<img width="451" alt="Screen Shot 2019-04-09 at 16 32 10" src="https://user-images.githubusercontent.com/11134669/55789792-2d910480-5ae5-11e9-9069-b6a0f5280d9a.png">

**Comment by vincentlel** [comment]
OK let me double check. Quick question: is the user supposed to test connection with the button, each he uses the plugin?

**Comment by myarjunar** [comment]
@VincentLel no, that button is only for checking whether the credentials are correct or not. the authentication will also be performed on the coverage call anyway.
