### ISSUE TITLE
Feature selection 

### ISSUE THREAD

**Issue by vincentlel** [earthdaily/qgis-plugin#34]
In the original discussion feature selection to get map was based on selection. Currently if we have an active layer of 10,000 features we cannot send API coverage for this entire layer but user may be interested to have maps for couple of objects.

Active layer drop down should have a default value with the layer selected in the "Layers" panel. In addition to the drop down list, it is required to have an option to have "selected objects only" ideally with the number.

**Comment by myarjunar** [comment]
currently, we are already supporting feature selection. but still lack of information shown to the user.

so for now, the layer dropdown list will show only the active layers (layers on map canvas). If the layer is in feature selection mode, then the plugin will call coverage search based on selected feature only, if not it will search based on the entire layer. I agree we should add checkbox which indicates whether to use the selected feature or not (if in feature selection mode). What I build is based on the original design, so it's nice to hear feedback. Thanks!

**Comment by vincentlel** [comment]
OK fine, as you mentioned this is not really intuitive for the users. Not sure how but would be nice to show that the selection will be used for the API Call

**Comment by myarjunar** [comment]
@VincentLel thanks for responding. also, what is the maximum number of features that will be processed if it turns out the selected layers has too many features?
