### ISSUE TITLE
Sensor selection

### ISSUE THREAD

**Issue by vincentlel** [earthdaily/qgis-plugin#35]
Sensor selection is an optional filter for the coverage. The default option should be "All" meaning that we will return all data available. As all data are cross calibrated in our platform, user can have several maps the same day and data will be consistent.

**Comment by myarjunar** [comment]
Ok, I will add `All sensors` option and set it as the default value. 
and also, could you confirm that all sensors type is already covered in the dropdown list?
thanks.

**Comment by vincentlel** [comment]
All sensors option means that you will not set a sensor filter in the API call.
