### ISSUE TITLE
Add RX zone area

### ISSUE THREAD

**Issue by mvmaltitz** [earthdaily/qgis-plugin#352]
Add the area into the left as per image
![Image](https://github.com/user-attachments/assets/67267206-2eb3-4a6c-9287-b990b9e40830)
![Image](https://github.com/user-attachments/assets/347d83d5-c171-44b4-b6d3-6cd9f36dde30)

**Comment by mal147** [comment]
![image](https://github.com/user-attachments/assets/43d0ea8a-776a-4460-a499-5fd909635143)
