### ISSUE TITLE
Hotspot - filters

### ISSUE THREAD

**Issue by mvmaltitz** [earthdaily/qgis-plugin#356]
@mal147 Please confirm if the filters are required
![Image](https://github.com/user-attachments/assets/26284b54-c194-402a-a9e4-c647fce61789)

**Comment by mvmaltitz** [comment]
@Samweli 
you can remove the Filters. They are no more a parameter for hotspot.

**Comment by Samweli** [comment]
@mvmaltitz  thanks will do.
