### ISSUE TITLE
Date selection persistence

### ISSUE THREAD

**Issue by vincentlel** [earthdaily/qgis-plugin#36]
Would it be possible to persist date entered by the user or we need to set default start date in a config file or in the setting.

**Comment by myarjunar** [comment]
in this ticket https://github.com/kartoza/geosys-qgis-plugin/issues/31 , @timlinux proposed that we set the default date range to last week. how about that?
yes, it is possible to keep the last entry from the user and show the last entry when the user opens the plugin again.

**Comment by vincentlel** [comment]
Default or persistence both option are fine to me

**Comment by vincentlel** [comment]
Default value is fine. But I would recommend one year delay.
