### ISSUE TITLE
Number of zones doesn't work on PNG/TIFF/SHP/KML

### ISSUE THREAD

**Issue by mal147** [earthdaily/qgis-plugin#365]

**Comment by mal147** [comment]
@osundwajeff still not working
![image](https://github.com/user-attachments/assets/dcb402a2-a296-45f5-9645-f630cbcd9ed4)

**Comment by SimF-EDAg** [comment]
It is working now on every map format :)

**Comment by Samweli** [comment]
> It is working now on every map format :) 

Thanks @SimF-EDAg
