### ISSUE TITLE
Add on RxMap request this parameter : &minzonesize=0.0247 to remove small polygon

### ISSUE THREAD

**Issue by mal147** [earthdaily/qgis-plugin#367]

**Comment by mal147** [comment]
To be consistent with our App, adding this parameter &minzonesize=0.0247 on RxMap, small polygons will be removed:
![Image](https://github.com/user-attachments/assets/55573c0e-b5da-4ccb-9707-8b051fe185ce)

**Comment by mal147** [comment]
still not working @osundwajeff 
![image](https://github.com/user-attachments/assets/c90927b5-093f-40fd-b4dd-f69b6f56e74e)

**Comment by osundwajeff** [comment]
@mal147 the changes on RX have not yet been merged

**Comment by mal147** [comment]
NDVI zoning map - OK
![image](https://github.com/user-attachments/assets/fd4c2bdf-1c56-4a04-8ac2-b0cb06246cf3)


Rx zoning map - OK
![image](https://github.com/user-attachments/assets/bb78597b-34e1-4480-bf03-a2ce585008ce)
