### ISSUE TITLE
issue on LAI - no thumbail and error on the export

### ISSUE THREAD

**Issue by mal147** [earthdaily/qgis-plugin#377]
![Image](https://github.com/user-attachments/assets/2b2fcf2e-629f-45de-ac25-66d09726ea72)
no thumbails

error on the export

![Image](https://github.com/user-attachments/assets/15ef5fea-3a0f-4ca8-8b0b-2f6bd40b44e0)

[QGIS_fields.zip](https://github.com/user-attachments/files/18163813/QGIS_fields.zip)
Using these 2 fields it must work with the crop TRITICALE
Fields should be located in France to be sure LAI is working

**Comment by Samweli** [comment]
@mal147 can you share the coverage search parameters? I wasn't able to fetch the coverages for the LAI map type using the shared area of interest, see attached screenshot.

![image](https://github.com/user-attachments/assets/9cabff01-9385-45bc-b05e-583319d7b5ac)

**Comment by mal147** [comment]
@Samweli 
Here is the API request to get LAI coverage for this geometry:
import requests
import json

url = "http://api.geosys-na.net/field-level-maps/v5/season-fields/catalog-imagery?coveragePercent=$gte:100&mask=auto&Image.Date=$between:2024-01-01|2024-06-30&Maps.Type=LAI"

payload = json.dumps({
  "seasonFields": [
    {
      "geometry": "MultiPolygon (((4.19880999999999993 48.25460300000000302, 4.20070399999999999 48.25416599999999789, 4.20203500000000041 48.25384499999999832, 4.20172300000000032 48.25335799999999864, 4.19982200000000017 48.252834, 4.19970100000000013 48.25282200000000188, 4.19957000000000047 48.252830000000003, 4.19786199999999976 48.25312300000000221, 4.19805399999999995 48.25360799999999983, 4.19766100000000009 48.25370399999999904, 4.19761200000000034 48.25375199999999865, 4.1978270000000002 48.25419800000000237, 4.19741799999999987 48.25429100000000204, 4.19805800000000051 48.25472599999999801, 4.19843300000000053 48.25467499999999887, 4.19880999999999993 48.25460300000000302)))",
      "crop": "TRITICALE"
    }
  ]
})
headers = {
  'Content-Type': 'application/json',
  'Authorization': '***'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)

And then to get LAI product:
import requests
import json

url = "http://api.geosys-na.net/field-level-maps/v5/maps/base-reference-map/LAI"

payload = json.dumps({
  "image": {
    "id": "sentinel-2-c1-l2a|S2A_T31UEP_20240625T103955_L2A"
  },
  "seasonField": {
    "geometry": "MultiPolygon (((4.19880999999999993 48.25460300000000302, 4.20070399999999999 48.25416599999999789, 4.20203500000000041 48.25384499999999832, 4.20172300000000032 48.25335799999999864, 4.19982200000000017 48.252834, 4.19970100000000013 48.25282200000000188, 4.19957000000000047 48.252830000000003, 4.19786199999999976 48.25312300000000221, 4.19805399999999995 48.25360799999999983, 4.19766100000000009 48.25370399999999904, 4.19761200000000034 48.25375199999999865, 4.1978270000000002 48.25419800000000237, 4.19741799999999987 48.25429100000000204, 4.19805800000000051 48.25472599999999801, 4.19843300000000053 48.25467499999999887, 4.19880999999999993 48.25460300000000302)))",
    "crop": "TRITICALE"
  }
})
headers = {
  'Content-Type': 'application/json',
  'Authorization': '***'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)

**Comment by mal147** [comment]
@Samweli 
Thumbail OK
![image](https://github.com/user-attachments/assets/33e69930-14f9-4f71-9302-a631410b8248)

Export still KO
![image](https://github.com/user-attachments/assets/611d722b-ddd9-48fb-8b6b-2277b15e636a)

**Comment by mal147** [comment]
This error can be on our side. I will let you know.
