### ISSUE TITLE
No coverage results for INSEASONFIELD_AVERAGE_NDVI / INSEASONFIELD_AVERAGE_LAI  / INSEASONFIELD_AVERAGE_REVERSE_NDVI / INSEASONFIELD_AVERAGE_REVERSE_LAI

### ISSUE THREAD

**Issue by mal147** [earthdaily/qgis-plugin#378]

**Comment by mal147** [comment]
![Image](https://github.com/user-attachments/assets/6fc96a3e-032a-490b-9c12-1b1f80f8c4e0)

**Comment by mal147** [comment]
it works but no thumbail @osundwajeff 
INSEASONFIELD_AVERAGE_NDVI and INSEASONFIELD_AVERAGE_LAI and INSEASONFIELD_AVERAGE_REVERSE_LAI
![image](https://github.com/user-attachments/assets/9b215e1d-fe73-4a22-a894-0af52651ba81)

**Comment by mal147** [comment]
Ok for INSEASONFIELD_AVERAGE_REVERSE_NDVI

![image](https://github.com/user-attachments/assets/8188c27a-aaef-4678-827f-488a3e3139fe)

**Comment by SimF-EDAg** [comment]
Same problem for OM and YGM

**Comment by mal147** [comment]
Thumbail are well display when LAI should be available:
![image](https://github.com/user-attachments/assets/af27b438-fc23-40f2-8ea3-42da6149bfdc)

We will look internally if it's normal to have coverage with LAI during the period of product is not available.

**Comment by mal147** [comment]
@Samweli & @osundwajeff 
for OM, YPM and YGM, the thumbail should be NDVI. Can you please add it ? I think it's the case on the QGIS plugin version we have in production ? Thank you

**Comment by Samweli** [comment]
Thanks @mal147.
