### ISSUE TITLE
INSEASONFIELD_AVERAGE_LAI  & INSEASONFIELD_AVERAGE_REVERSE_LAI don't work

### ISSUE THREAD

**Issue by mal147** [earthdaily/qgis-plugin#395]

**Comment by mal147** [comment]
![Image](https://github.com/user-attachments/assets/af922bcf-bb9f-4c74-8c9f-0385f1feca59)
![Image](https://github.com/user-attachments/assets/a9178b9e-711b-4568-a8c4-213062afd0c8)

when selecting only images with thumbnail

**Comment by mal147** [comment]
On example on Postman (working on my side).

import requests
import json

url = "http://api.geosys-na.net/field-level-maps/v5/maps/model-map/INSEASONFIELD_AVERAGE_LAI?storeRequest=false"

payload = json.dumps({
  "image": {
    "id": "sentinel-2-c1-l2a|S2B_T31TCJ_20240613T105852_L2A"
  },
  "nPlanned": 30,
  "seasonField": {
    "geometry": "POLYGON ((1.61537731 43.78848583, 1.61684651 43.7894463, 1.61770907 43.79003285, 1.61894228 43.78913373, 1.61936197 43.78880657, 1.61942638 43.78881247, 1.62124026 43.78996256, 1.62194642 43.78885897, 1.62216876 43.78837163, 1.62182479 43.78818505, 1.62139648 43.7878835, 1.6203123 43.78692047, 1.62007478 43.78673701, 1.61985236 43.78659583, 1.6188567600000001 43.78730854, 1.61848324 43.78707021, 1.6184173 43.78708124, 1.61771698 43.7866527, 1.6171823 43.78661626, 1.61704216 43.78668636, 1.61537731 43.78848583))",
    "crop": "WHEAT_WINTER_SOFT"
  },
  "gain": 1,
  "offset": 0
})
headers = {
  'Content-Type': 'application/json',
  'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRDQjZGQ0NEM0MyMjI5QzdFRTk1QTZBOUJDQkRCRTI2RjMwNjg1ODRSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6IjNMYjh6VHdpS2NmdWxhYXB2TDItSnZNR2hZUSJ9.eyJuYmYiOjE3MzUyOTQ1MDcsImV4cCI6MTczNTI5ODEwNywiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtbmEuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1uYS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJrZXlfYWNjb3VudF90ZWFtIiwic3ViIjoiMTAwMTExMjM1IiwiYXV0aF90aW1lIjoxNzM1Mjk0NTA3LCJpZHAiOiJsb2NhbCIsImdlbzZfc3ViIjoiUWdJNk9yYlJqRXNSZmlOWnRWUHA0IiwiaWF0IjoxNzM1Mjk0NTA3LCJzY29wZSI6WyJvcGVuaWQiLCJvZmZsaW5lX2FjY2VzcyJdLCJhbXIiOlsicGFzc3dvcmQiXX0.BKnsct7LZwgCMZikvE7Kyj7KEXH00K3sOTyHem9jQzN50I876Ymu1gp1FxMmagPntWjFFvJDtykfsImPljLA_ioQ8xLShZ2K6mEOhT9on10zBmN2eywQ4rh60jnT6ACpUBuj2-qPlEk4WgiZ-IA1V8iO-SMXR2ovl_MfbzmDD5qAoW7TYru9UMet8B784Z0wnTyXhKFpyQYykB4BsNgZFyJUmHKIGD-j8zisbEaF0xAvrBhX_yzW2ya8VKYGfaQX1uS7jXdoyfLr_J2HvMO_w84wvAozOcc8F37rgqXXtu3JNY7NDEypEYh39RXOwkn_1VErTdfD789tZE_0uijTgw'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)



import requests
import json

url = "http://api.geosys-na.net/field-level-maps/v5/maps/model-map/INSEASONFIELD_AVERAGE_REVERSE_LAI?storeRequest=false"

payload = json.dumps({
  "image": {
    "id": "sentinel-2-c1-l2a|S2B_T31TCJ_20240613T105852_L2A"
  },
  "nPlanned": 30,
  "seasonField": {
    "geometry": "POLYGON ((1.61537731 43.78848583, 1.61684651 43.7894463, 1.61770907 43.79003285, 1.61894228 43.78913373, 1.61936197 43.78880657, 1.61942638 43.78881247, 1.62124026 43.78996256, 1.62194642 43.78885897, 1.62216876 43.78837163, 1.62182479 43.78818505, 1.62139648 43.7878835, 1.6203123 43.78692047, 1.62007478 43.78673701, 1.61985236 43.78659583, 1.6188567600000001 43.78730854, 1.61848324 43.78707021, 1.6184173 43.78708124, 1.61771698 43.7866527, 1.6171823 43.78661626, 1.61704216 43.78668636, 1.61537731 43.78848583))",
    "crop": "WHEAT_WINTER_SOFT"
  },
  "gain": 1,
  "offset": 0
})
headers = {
  'Content-Type': 'application/json',
  'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRDQjZGQ0NEM0MyMjI5QzdFRTk1QTZBOUJDQkRCRTI2RjMwNjg1ODRSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6IjNMYjh6VHdpS2NmdWxhYXB2TDItSnZNR2hZUSJ9.eyJuYmYiOjE3MzUyOTQ1MDcsImV4cCI6MTczNTI5ODEwNywiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtbmEuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1uYS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJrZXlfYWNjb3VudF90ZWFtIiwic3ViIjoiMTAwMTExMjM1IiwiYXV0aF90aW1lIjoxNzM1Mjk0NTA3LCJpZHAiOiJsb2NhbCIsImdlbzZfc3ViIjoiUWdJNk9yYlJqRXNSZmlOWnRWUHA0IiwiaWF0IjoxNzM1Mjk0NTA3LCJzY29wZSI6WyJvcGVuaWQiLCJvZmZsaW5lX2FjY2VzcyJdLCJhbXIiOlsicGFzc3dvcmQiXX0.BKnsct7LZwgCMZikvE7Kyj7KEXH00K3sOTyHem9jQzN50I876Ymu1gp1FxMmagPntWjFFvJDtykfsImPljLA_ioQ8xLShZ2K6mEOhT9on10zBmN2eywQ4rh60jnT6ACpUBuj2-qPlEk4WgiZ-IA1V8iO-SMXR2ovl_MfbzmDD5qAoW7TYru9UMet8B784Z0wnTyXhKFpyQYykB4BsNgZFyJUmHKIGD-j8zisbEaF0xAvrBhX_yzW2ya8VKYGfaQX1uS7jXdoyfLr_J2HvMO_w84wvAozOcc8F37rgqXXtu3JNY7NDEypEYh39RXOwkn_1VErTdfD789tZE_0uijTgw'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)

**Comment by mal147** [comment]
Can you please have a look @osundwajeff @mvmaltitz & @Samweli ? Thank you

**Comment by Samweli** [comment]
@mal147 this is similar to https://github.com/earthdaily/qgis-plugin/issues/396 right?

**Comment by mal147** [comment]
@Samweli no, even I select an image with a thumbnail, I have this error whereas it works on Postman (see my above comment). Thanks

**Comment by mal147** [comment]
Good to me ! Thank you @Samweli
