### ISSUE TITLE
INSEASONFIELD_AVERAGE_LAI  & INSEASONFIELD_AVERAGE_REVERSE_LAI must have the same coverage as LAI

### ISSUE THREAD

**Issue by mal147** [earthdaily/qgis-plugin#396]
LAI coverage
![Image](https://github.com/user-attachments/assets/47663f55-543a-4b69-8946-b3c53f101ba6)

INSEASONFIELD_AVERAGE_LAI  & INSEASONFIELD_AVERAGE_REVERSE_LAI coverage
![Image](https://github.com/user-attachments/assets/10fe5b4a-2836-4e8e-8a46-cb32824c4f0d)

**Comment by mal147** [comment]
Can you please have a look @Samweli ? Thank you

**Comment by Samweli** [comment]
> Can you please have a look @Samweli ? Thank you

Ok @mal147, I will get back to you once I confirm the issue.

**Comment by Samweli** [comment]
@mal147 by same coverage do we mean they should have the same thumbnails? On INSEASONFIELD_AVERAGE_LAI and INSEASONFIELD_AVERAGE_REVERSE_LAI we have to pass additional body parameters in order to fetch the thumbnails, do we have to ask users for these parameters?

 ```python
  "nPlanned": number,
  "nMin": number
  "nMax": number
 ```

**Comment by mal147** [comment]
@Samweli No, the thumbnails must be different from those of the LAI. The visible ones for INSEASONFIELD_AVERAGE_LAI and INSEASONFIELD_AVERAGE_REVERSE_LAI products are correct. 
However, there is a list of images without thumbnails (where LAI is not available) and those images must should not be available or visible when requesting the coverage of these two products.
![image](https://github.com/user-attachments/assets/21200086-be75-4d48-8eed-fbfa694818a1)

**Comment by Samweli** [comment]
> @Samweli No, the thumbnails must be different from those of the LAI. The visible ones for INSEASONFIELD_AVERAGE_LAI and INSEASONFIELD_AVERAGE_REVERSE_LAI products are correct.

Right @mal147, I have tried a similar coverage search using Postman and I also got the coverages where LAI is not available, see attached screenshot

![image](https://github.com/user-attachments/assets/857fcb29-591d-42e2-8a54-0548c7093443)

example on postman 

```python
import requests
import json

url = "http://api.geosys-na.net/field-level-maps/v5/season-fields/catalog-imagery?coveragePercent=$gte:100&$limit=1000&Maps.Type=INSEASONFIELD_AVERAGE_LAI\"&image.date=$between:2024-05-31|2024-07-20"

payload = json.dumps({
  "seasonFields": [
    {
      "geometry": "MultiPolygon (((4.19880999999999993 48.25460300000000302, 4.20070399999999999 48.25416599999999789, 4.20203500000000041 48.25384499999999832, 4.20172300000000032 48.25335799999999864, 4.19982200000000017 48.252834, 4.19970100000000013 48.25282200000000188, 4.19957000000000047 48.252830000000003, 4.19786199999999976 48.25312300000000221, 4.19805399999999995 48.25360799999999983, 4.19766100000000009 48.25370399999999904, 4.19761200000000034 48.25375199999999865, 4.1978270000000002 48.25419800000000237, 4.19741799999999987 48.25429100000000204, 4.19805800000000051 48.25472599999999801, 4.19843300000000053 48.25467499999999887, 4.19880999999999993 48.25460300000000302)))",
      "crop": "TRITICALE"
    }
  ]
})
headers = {
  'Content-Type': 'application/json',
  'Authorization': 'Bearer {replace_with_token}'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)


```

Getting a thumbnail for image with id `landsat-c2l2-sr|LC08_L2SP_197027_20240719_20240723_02_T1_SR` results into the `coverage_not_found` message

![image](https://github.com/user-attachments/assets/8dd377ec-eb4a-4773-b133-9e399b1cbabf)

**Comment by mal147** [comment]
Hi @Samweli, 
Ok, you can let that as is it now. 
INSEASONFIELD_AVERAGE_LAI and INSEASONFIELD_AVERAGE_REVERSE_LAI products are not on the maptype list, I will ask to my IT colleagues to add them and then automactically, it will resolve this issue.

**Comment by Samweli** [comment]
> Hi @Samweli, Ok, you can let that as is it now. INSEASONFIELD_AVERAGE_LAI and INSEASONFIELD_AVERAGE_REVERSE_LAI products are not on the maptype list, I will ask to my IT colleagues to add them and then automactically, it will resolve this issue.

Thanks @mal147
