### ISSUE TITLE
No limit on the values on RxMap

### ISSUE THREAD

**Issue by mal147** [earthdaily/qgis-plugin#401]
On RxMap creation, the user must be able to put a value higher than 100.
Here is limited to 100 but it must be able to put 1000 or 10000 or more.
Thank you

![Image](https://github.com/user-attachments/assets/a968619d-c858-44df-877d-1fd5aa825b3d)

**Comment by mal147** [comment]
@Samweli can you please fix this issue? Thank you

**Comment by Samweli** [comment]
> @Samweli can you please fix this issue? Thank you

Sure @mal147

**Comment by Samweli** [comment]
@mal147 the input widget allows an upper maximum value of `2147483647` for numbers, can we use that or you explicity doesn't want any limit? see PR https://github.com/earthdaily/qgis-plugin/pull/405 as an example. thanks.

**Comment by mal147** [comment]
You can use this maximum value of 2147483647, that's perfect @Samweli, thank you very much!

**Comment by mal147** [comment]
Thank you @Samweli 
![image](https://github.com/user-attachments/assets/d045f43b-985f-4b11-b83e-5327fa410440)
