### ISSUE TITLE
hotspots are not working on ELEVATION map

### ISSUE THREAD

**Issue by mal147** [earthdaily/qgis-plugin#403]
![Image](https://github.com/user-attachments/assets/e0d1ee0f-dfd5-4bf7-8b94-1ad6842fa365)

Postman example:
import requests
import json

url = "https://hotspots.aws.geosys.com/hotspots-processor/topology-map?Type=Zone&ZonesCount=5&%24epsg-out=4326"

payload = json.dumps({
  "geometry": "POLYGON ((-56.785919346530768 -21.208154463301554 , -56.79078750820733 -21.206043784434833 , -56.790973809206818 -21.206069651656232 , -56.791373799079636 -21.197107091323097 , -56.785129186971687 -21.196010916846863 , -56.781397554331065 -21.19535575112814 , -56.777108478217059 -21.202038412606473 , -56.778435977920665 -21.211398619037478 , -56.785919346530768 -21.208154463301554))"
})
headers = {
  'Content-Type': 'application/json',
  'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRDQjZGQ0NEM0MyMjI5QzdFRTk1QTZBOUJDQkRCRTI2RjMwNjg1ODRSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6IjNMYjh6VHdpS2NmdWxhYXB2TDItSnZNR2hZUSJ9.eyJuYmYiOjE3MzU2MzQwMDcsImV4cCI6MTczNTYzNzYwNywiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5nZW9zeXMtbmEuY29tL3YyLjEiLCJhdWQiOiJodHRwczovL2lkZW50aXR5Lmdlb3N5cy1uYS5jb20vdjIuMS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJrZXlfYWNjb3VudF90ZWFtIiwic3ViIjoiMTAwMTExMjM1IiwiYXV0aF90aW1lIjoxNzM1NjM0MDA3LCJpZHAiOiJsb2NhbCIsImdlbzZfc3ViIjoiUWdJNk9yYlJqRXNSZmlOWnRWUHA0IiwiaWF0IjoxNzM1NjM0MDA3LCJzY29wZSI6WyJvcGVuaWQiLCJvZmZsaW5lX2FjY2VzcyJdLCJhbXIiOlsicGFzc3dvcmQiXX0.lULkhBHIX_ANCRoMB5wuhyYOJR_bkZh8WH-wefHgNWzDT84lM3mmLtsK7LMFrJmkwMg6Uz_kxSnQcQaCa6VjlHR-s9VusTo45qKCzTacqYOaOViLR8Eqwg74RlGvOopmkKbY-8MIxCGkNlvnJ3g5TaonWzyLadqWyXRJNSj-W75eSGoHhhIlzwFvkMrQIZ1HQqHFYWnLdkc9KAvk__HAzrVuD6nj3D_Awn8S4o0AlQ1PWcbZ93CIJKXENPb-7jCL0teA6m_aEsuZL6-Gj5mNziZzeqhUsFNQIcMSbC8opPofYuBaZXfKLiZv1U6Zy2VdHOWKVD_JDdtIOyj0_Ca8jw'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)

answer:

{
    "Metadata": {
        "geometry": "POLYGON ((-56.785919346530768 -21.208154463301554 , -56.79078750820733 -21.206043784434833 , -56.790973809206818 -21.206069651656232 , -56.791373799079636 -21.197107091323097 , -56.785129186971687 -21.196010916846863 , -56.781397554331065 -21.19535575112814 , -56.777108478217059 -21.202038412606473 , -56.778435977920665 -21.211398619037478 , -56.785919346530768 -21.208154463301554))"
    },
    "OutputData": {
        "Hotspots": [
            {
                "value": 0,
                "segmentId": 1,
                "position": "PointOnSurface",
                "geometry": "POINT (-56.78796958753308 -21.205750172237195)"
            },
            {
                "value": 0,
                "segmentId": 2,
                "position": "PointOnSurface",
                "geometry": "POINT (-56.786924617817235 -21.204536965195878)"
            },
            {
                "value": 0,
                "segmentId": 3,
                "position": "PointOnSurface",
                "geometry": "POINT (-56.78446169431769 -21.2037710544526)"
            },
            {
                "value": 0,
                "segmentId": 4,
                "position": "PointOnSurface",
                "geometry": "POINT (-56.78222560975056 -21.202382167681954)"
            },
            {
                "value": 0,
                "segmentId": 5,
                "position": "PointOnSurface",
                "geometry": "POINT (-56.780209483075254 -21.1984745070342)"
            }
        ]
    }
}

**Comment by Samweli** [comment]
@mal147 I have created PR that returns the old support for `ELEVATION` hotspots here https://github.com/earthdaily/qgis-plugin/pull/407 , I once removed the support due to the following issue comment https://github.com/earthdaily/qgis-plugin/issues/355#issuecomment-2541441962. Did you mean to remove some other map product support?

**Comment by mal147** [comment]
@Samweli we have the Elevation product on the plugin so we would like to have the new way to have hotspots using the new hotspot API: here for topology map 
url = "https://hotspots.aws.geosys.com/hotspots-processor/topology-map"

**Comment by mal147** [comment]
Looks good ! Thank you @Samweli 
![image](https://github.com/user-attachments/assets/3695afba-795e-42b2-98b2-0c1ec6cb18c4)
