### ISSUE TITLE
Difference map not working 

### ISSUE THREAD

**Issue by vincentlel** [earthdaily/qgis-plugin#63]
**Describe the bug**
The difference map button should be enable only when 2 EVI or NDVI maps have been selected in the coverage panel. The two selected date will be used as parameter of the difference map end point.

**Comment by myarjunar** [comment]
Hi @VincentLel , could you elaborate more on what is not working? I tested it on my local machine and the difference map appears on the map creation panel. 
![Apr-23-2019 14-26-59](https://user-images.githubusercontent.com/11134669/56562616-fe45c180-65d3-11e9-8979-69e8fea66bbd.gif)

**Comment by vincentlel** [comment]
Hi Rohmat, I confirmed that this is now working for me as well. The behavior of the button is as well fine. I think we can close this one.
