### ISSUE TITLE
Issue in SaMZ creation

### ISSUE THREAD

**Issue by vincentlel** [earthdaily/qgis-plugin#64]
**Describe the bug**
SaMZ is a zoning method that compile several images to create zones:
- when the selection is empty in the coverage screen then you need to call SaMZ (see SaMZ Auto in the postman collection). Our platform will automatically select 5 images and create zones)
- when the selection is not empty, you need to call SaMZ and set selected images dates to be used (see SaMZ Custom in the Postman collection) 

Currently if several image are selected, the tool generates several maps and it should not be the case.

**Comment by myarjunar** [comment]
Hi @VincentLel , I am unable to create the custom SaMZ map using multiple image dates. it returns internal server error message:
```
{
    "code": "internal_error",
    "message": "internal_error: An error has occured",
    "id": "07yF0HOakEmB10iUPhCSpA"
}
```

auto SaMZ map works fine (no image date or single image date).

**Comment by myarjunar** [comment]
could you please also share with me dataset for performing SaMZ map request? The one in the postman is not working. Thanks..

**Comment by vincentlel** [comment]
Hi Rohmat, here is the curl of the call that is working on my side.
{
  "seasonField": {
    "id": "zgqbr35",
    "customerExternalId": "QUGZKsiYQoJ4QC3ug17lWEGM7mXdKoSIWSA44xcSUik="
  },
  "_links": {
    "self": "https://bridge.preprod.geosys-na.com:443/field-level-maps/v4/season-fields/zgqbr35/management-zones-map/SAMZ?ZoneCount=5&imageDates=2018-08-09&imageDates=2018-08-04&imageDates=2018-08-02&imageDates=2018-08-01&imageDates=2018-07-28",
    "worldFile": "https://bridge.preprod.geosys-na.com:443/field-level-maps/v4/season-fields/zgqbr35/management-zones-map/SAMZ/world-file.pgw?ZoneCount=5&imageDates=2018-08-09&imageDates=2018-08-04&imageDates=2018-08-02&imageDates=2018-08-01&imageDates=2018-07-28",
    "thumbnail": "https://bridge.preprod.geosys-na.com:443/field-level-maps/v4/season-fields/zgqbr35/management-zones-map/SAMZ/thumbnail.png?ZoneCount=5&imageDates=2018-08-09&imageDates=2018-08-04&imageDates=2018-08-02&imageDates=2018-08-01&imageDates=2018-07-28",
    "legend": "https://bridge.preprod.geosys-na.com:443/field-level-maps/v4/season-fields/zgqbr35/management-zones-map/SAMZ/legend.png?ZoneCount=5&imageDates=2018-08-09&imageDates=2018-08-04&imageDates=2018-08-02&imageDates=2018-08-01&imageDates=2018-07-28",
    "image:image/png": "https://bridge.preprod.geosys-na.com:443/field-level-maps/v4/season-fields/zgqbr35/management-zones-map/SAMZ/image.png?ZoneCount=5&imageDates=2018-08-09&imageDates=2018-08-04&imageDates=2018-08-02&imageDates=2018-08-01&imageDates=2018-07-28",
    "image:image/tiff+zip": "https://bridge.preprod.geosys-na.com:443/field-level-maps/v4/season-fields/zgqbr35/management-zones-map/SAMZ/image.tiff.zip?ZoneCount=5&imageDates=2018-08-09&imageDates=2018-08-04&imageDates=2018-08-02&imageDates=2018-08-01&imageDates=2018-07-28",
    "image:application/shp+zip": "https://bridge.preprod.geosys-na.com:443/field-level-maps/v4/season-fields/zgqbr35/management-zones-map/SAMZ/image.shp.zip?ZoneCount=5&imageDates=2018-08-09&imageDates=2018-08-04&imageDates=2018-08-02&imageDates=2018-08-01&imageDates=2018-07-28",
    "image:application/vnd.google-earth.kmz": "https://bridge.preprod.geosys-na.com:443/field-level-maps/v4/season-fields/zgqbr35/management-zones-map/SAMZ/image.kmz?ZoneCount=5&imageDates=2018-08-09&imageDates=2018-08-04&imageDates=2018-08-02&imageDates=2018-08-01&imageDates=2018-07-28"
  },
  "index": 0,
  "legend": {
    "stat": {
      "fieldVariability": "High",
      "mostVariableZone": "4",
      "highestInterZoneVariability": [
        "5",
        "3"
      ],
      "fieldProductivityIndex": 49.0,
      "fieldVariabilityIndex": 0.29585462197191981,
      "max": 5.0,
      "mean": 3.090992,
      "min": 1.0
    },
    "ranges": [
      {
        "name": "1",
        "productivityIndex": 30.0,
        "fieldAreaPercent": 13,
        "variabilityIndex": 12170990.461398652,
        "color": {
          "r": 123,
          "g": 254,
          "b": 205
        },
        "numberOfPixels": 8386,
        "maxValue": 1.0,
        "minValue": 1.0
      },
      {
        "name": "2",
        "productivityIndex": 30.0,
        "fieldAreaPercent": 22,
        "variabilityIndex": 4314091.2947504865,
        "color": {
          "r": 179,
          "g": 176,
          "b": 123
        },
        "numberOfPixels": 14842,
        "maxValue": 2.0,
        "minValue": 2.0
      },
      {
        "name": "3",
        "productivityIndex": 38.0,
        "fieldAreaPercent": 20,
        "variabilityIndex": 3615013.6675021597,
        "color": {
          "r": 237,
          "g": 254,
          "b": 165
        },
        "numberOfPixels": 13201,
        "maxValue": 3.0,
        "minValue": 3.0
      },
      {
        "name": "4",
        "productivityIndex": 66.0,
        "fieldAreaPercent": 33,
        "variabilityIndex": 18919792.556126181,
        "color": {
          "r": 255,
          "g": 186,
          "b": 117
        },
        "numberOfPixels": 21219,
        "maxValue": 4.0,
        "minValue": 4.0
      },
      {
        "name": "5",
        "productivityIndex": 83.0,
        "fieldAreaPercent": 12,
        "variabilityIndex": 3490810.028226743,
        "color": {
          "r": 170,
          "g": 127,
          "b": 255
        },
        "numberOfPixels": 8193,
        "maxValue": 5.0,
        "minValue": 5.0
      }
    ],
    "_links": {
      "self:image/png": "https://api-pp.geosys-na.net/documents/v1/s/ATjArnYjXU9OoqvIvPWw2XYEcSe3Dp2KS7HlqkfCo8gu/0IDgLlGu0kqxdmENTGIuoQ"
    }
  }
}

**Comment by vincentlel** [comment]
This request is included in the Postman collection I shared with the name Custom SaMZ

**Comment by vincentlel** [comment]
Here is the WKT on PPUS "POLYGON ((-100.2976835603640211 39.00266205900376804, -100.2801983085272326 39.00222898775084701, -100.28171405791246684 38.99161874205421441, -100.29714222129787515 38.99213301416705946, -100.2976835603640211 39.00266205900376804))

**Comment by myarjunar** [comment]
> This request is included in the Postman collection I shared with the name Custom SaMZ

@VincentLel  Sorry I was unaware that I need to run another coverage call to get all variables required by the SaMZ request to be populated. I am able to perform a SaMZ request now.

Thank you very much.
