### ISSUE TITLE
Impossible to get elevation map 

### ISSUE THREAD

**Issue by vincentlel** [earthdaily/qgis-plugin#67]
**Describe the bug**
Impossible to get elevation map out of the plugin. Elevation is not related with coverage date (no image date parameter), so when user selects "Elevation", we should go directly to export format and then generate map.

**Comment by myarjunar** [comment]
@VincentLel but it still requires SeasonField ID right? I think we still need to perform a coverage call to get the SeasonField ID and go straight to map creation panel once it finished.

**Comment by vincentlel** [comment]
Yes you need a field ID to call this API
