### ISSUE TITLE
Create a legend for maps in GeoSys panel

### ISSUE THREAD

**Issue by timlinux** [earthdaily/qgis-plugin#71]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/178003/56498881-acca0380-64fb-11e9-83f1-af349d7db96e.png">

**Comment by vincentlel** [comment]
Let discuss this one, once bugs are solved, lower priority than core features.

**Comment by ghost** [comment]
Hi everyone, I am taking the opportunity of this ticket to ask about the SAMZ maps legend.
In Bridge Data Viewer (the ancestor of this plugin), we used to have the possibility to export a PDF report containing a map, a legend and a diagram with the number of hectares in each zone. It was very useful to understand the management zones (please see screenshot).
The SAMZ map legend as it is today is quite useless as we don't clearly know which zone from 1 to 5 is the most productive, the least productive, in the average and so on.

We don't necessarily need the diagram but the legend should include the link to productivity.
Thank you!
[1┴Ò_SAMZReport_2015-07-24.pdf](https://github.com/GEOSYS/qgis-plugin/files/3216996/1.O_SAMZReport_2015-07-24.pdf)
