### ISSUE TITLE
Colorcomposition map thumbnail size is sensor-related

### ISSUE THREAD

**Issue by ghost** [earthdaily/qgis-plugin#85]
**Describe the bug**
When I request colorcomposition maps on a single field (out of 4), the thumbnails are not all the same size. They depend on sensor type.

**To Reproduce**
1. Load the attached zipped layer into QGIS (EU platform)
2. Select field called 'mafalda' or 'pocahontas'
3. Tick the 'Selected features only' box
4. Choose COLORCOMPOSITION
5. ALL SENSORS
6. 2019-04-01 to today

**Expected behavior**
All the thumbnails should be the same height/width, no matter the sensor and no matter the field size/shape.

**Screenshots**
![image](https://user-images.githubusercontent.com/50585928/57705799-ce368f00-7664-11e9-91ff-2021562123fd.png)

Let me know if you have questions.

**Comment by ghost** [comment]
@myarjunar I didn't find anything similar in the existing issues. That's why I created this one. I hope it's not a duplicate.

**Comment by vincentlel** [comment]
This is not a blocking issue and this might be related image native resolution as L8 Enhanced is at 15 m and S2 at 10 m. There is not resampling at 5 m on this map type. This minor issue can be classified as enhancement.
