### ISSUE TITLE
Coverage obtaining error

### ISSUE THREAD

**Issue by XiVar** [earthdaily/qgis-plugin#91]
Hello
I've encountered a problem while trying to get the coverage. This is exactly the same case as in [https://github.com/GEOSYS/qgis-plugin/issues/76](url), but this case is already closed as its author handled the issue by himself. I am a fresh user of the plugin, and kind of newbie to the programming.

Basically I have created a shapefile, but whatever settings I use it won't let me get the coverage. Is there any chance it's somehow caused by connection problem? I mean I had hard times getting authentication (turned out it is US region for me while I expected Europe). Also I am on a trial version as I need the plugin for just a while. If needed I will attach anything possible, but maybe there is some known solution by now.
Thanks in advance

**Comment by vincentlel** [comment]
Can we you share the WKT of the geoemtry you are using? I will run a quick test to see what is exactly the issue.

**Comment by XiVar** [comment]
That's the layer I tried to use. It's a single polygon layer. In the meantime i tried again, and this time I didn't get that error, however regardless of the settings and parameters I don't get any results. This time it could be my fault, but I tried a lot of combinations already

[vector.zip](https://github.com/GEOSYS/qgis-plugin/files/3892979/vector.zip)

**Comment by vincentlel** [comment]
I tried with your shapefile and it appears that we currently have no images loaded on the area you are trying to access. Could you please let us know what territory you want to cover and what period of the year you are interested in.
