### ISSUE TITLE
Zoned  maps

### ISSUE THREAD

**Issue by vincentlel** [earthdaily/qgis-plugin#99]
Vegetation index map will group pixel into classes but each class is not necessarily a contiguous set of pixel, when is asking for a vector map, our map engine will vectorize all pixels and the output can be cumbersome and heavy. We provide an option to create “cleaned” zones based on the selected map. What we need from you is to:

*	Change the label on the map parameter screen from “SAMZ zone” by “Number of zones”. the default value is Null
*	When this property is filled by the user (no persistence of this user input) add in the get request the following parameter: ?zoning=true&zoneCount=X where X is the number of zone set by the user. This is available for all maps except SaMZ that is by definition a zoned map (so you will continue to use the number of zone set by the user) and color composition.
*	Postman collection shared by mail provides examples on several map types of this zoning option

Here is one example of the Get map URL with zoning option:

https://bridge.preprod.geosys-na.com/field-level-maps/v4/season-fields/5nl35la/coverage/2019-11-25/base-reference-map/INSEASON_NDVI?zoning=true&zoneCount=12

Zoning option is available for all map type except SaMZ and color composition

**Comment by timlinux** [comment]
Omit zoning flags if zoneCount <1

![image](https://user-images.githubusercontent.com/178003/77074034-155d8100-69e8-11ea-9991-c2c1d99c2c35.png)

**Comment by vincentlel** [comment]
good to go

**Comment by Samweli** [comment]
Closed in https://github.com/GEOSYS/qgis-plugin/pull/107
